// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Default Suite', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('View Info External Tutor', async function() {
    // Test name: View Info External Tutor
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    await driver.get("http://localhost:8080/")
    // 2 | setWindowSize | 1600x866 |  | 
    await driver.manage().window().setRect(1600, 866)
    // 3 | type | id=inputUsername | p.penna@unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("p.penna@unisa.it")
    // 4 | type | id=inputPassword | PenPaola1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("PenPaola1")
    // 5 | click | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 6 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 7 | click | css=.nav-primary > .nav-item:nth-child(3) > a |  | 
    await driver.findElement(By.css(".nav-primary > .nav-item:nth-child(3) > a")).click()
    // 8 | click | id=tipo |  | 
    await driver.findElement(By.id("tipo")).click()
    // 9 | select | id=tipo | label=Tutor Esterni | 
    {
      const dropdown = await driver.findElement(By.id("tipo"))
      await dropdown.findElement(By.xpath("//option[. = 'Tutor Esterni']")).click()
    }
    // 10 | click | id=tipo |  | 
    await driver.findElement(By.id("tipo")).click()
    // 11 | click | css=.card:nth-child(2) .btn |  | 
    await driver.findElement(By.css(".card:nth-child(2) .btn")).click()
    // 12 | close |  |  | 
    await driver.close()
  })
  it('View Info Host Organization', async function() {
    // Test name: View Info Host Organization
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    await driver.get("http://localhost:8080/")
    // 2 | setWindowSize | 1600x866 |  | 
    await driver.manage().window().setRect(1600, 866)
    // 3 | type | id=inputUsername | p.penna@unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("p.penna@unisa.it")
    // 4 | type | id=inputPassword | PenPaola1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("PenPaola1")
    // 5 | click | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 6 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 7 | click | css=.nav-primary > .nav-item:nth-child(3) > a |  | 
    await driver.findElement(By.css(".nav-primary > .nav-item:nth-child(3) > a")).click()
    // 8 | click | id=tipo |  | 
    await driver.findElement(By.id("tipo")).click()
    // 9 | select | id=tipo | label=Organizzazioni Ospitanti | 
    {
      const dropdown = await driver.findElement(By.id("tipo"))
      await dropdown.findElement(By.xpath("//option[. = 'Organizzazioni Ospitanti']")).click()
    }
    // 10 | click | id=tipo |  | 
    await driver.findElement(By.id("tipo")).click()
    // 11 | click | css=.card:nth-child(2) .btn |  | 
    await driver.findElement(By.css(".card:nth-child(2) .btn")).click()
    // 12 | close |  |  | 
    await driver.close()
  })
  it('View List External Tutor', async function() {
    // Test name: View List External Tutor
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    await driver.get("http://localhost:8080/")
    // 2 | setWindowSize | 1600x866 |  | 
    await driver.manage().window().setRect(1600, 866)
    // 3 | type | id=inputUsername | p.penna@unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("p.penna@unisa.it")
    // 4 | type | id=inputPassword | PenPaola1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("PenPaola1")
    // 5 | click | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 6 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 7 | click | css=.nav-item:nth-child(3) p |  | 
    await driver.findElement(By.css(".nav-item:nth-child(3) p")).click()
    // 8 | click | id=tipo |  | 
    await driver.findElement(By.id("tipo")).click()
    // 9 | select | id=tipo | label=Tutor Esterni | 
    {
      const dropdown = await driver.findElement(By.id("tipo"))
      await dropdown.findElement(By.xpath("//option[. = 'Tutor Esterni']")).click()
    }
    // 10 | click | id=tipo |  | 
    await driver.findElement(By.id("tipo")).click()
    // 11 | close |  |  | 
    await driver.close()
  })
  it('View List Host Organization', async function() {
    // Test name: View List Host Organization
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    await driver.get("http://localhost:8080/")
    // 2 | setWindowSize | 1600x866 |  | 
    await driver.manage().window().setRect(1600, 866)
    // 3 | type | id=inputUsername | p.penna@unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("p.penna@unisa.it")
    // 4 | type | id=inputPassword | PenPaola1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("PenPaola1")
    // 5 | click | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 6 | click | css=.nav-item:nth-child(3) p |  | 
    await driver.findElement(By.css(".nav-item:nth-child(3) p")).click()
    // 7 | click | id=tipo |  | 
    await driver.findElement(By.id("tipo")).click()
    // 8 | select | id=tipo | label=Organizzazioni Ospitanti | 
    {
      const dropdown = await driver.findElement(By.id("tipo"))
      await dropdown.findElement(By.xpath("//option[. = 'Organizzazioni Ospitanti']")).click()
    }
    // 9 | click | id=tipo |  | 
    await driver.findElement(By.id("tipo")).click()
    // 10 | close |  |  | 
    await driver.close()
  })
  it('View Notification', async function() {
    // Test name: View Notification
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    await driver.get("http://localhost:8080/")
    // 2 | setWindowSize | 1600x866 |  | 
    await driver.manage().window().setRect(1600, 866)
    // 3 | type | id=inputUsername | p.penna@unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("p.penna@unisa.it")
    // 4 | type | id=inputPassword | PenPaola1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("PenPaola1")
    // 5 | sendKeys | id=inputPassword | ${KEY_ENTER} | 
    await driver.findElement(By.id("inputPassword")).sendKeys(Key.ENTER)
    // 6 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 7 | click | id=open-notification |  | 
    await driver.findElement(By.id("open-notification")).click()
    // 8 | close |  |  | 
    await driver.close()
  })
  it('View Request Document and Disapprove', async function() {
    // Test name: View Request Document and Disapprove
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    await driver.get("http://localhost:8080/")
    // 2 | setWindowSize | 1600x866 |  | 
    await driver.manage().window().setRect(1600, 866)
    // 3 | type | id=inputUsername | d.devito@studenti.unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("d.devito@studenti.unisa.it")
    // 4 | type | id=inputPassword | DannyDeVito1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("DannyDeVito1")
    // 5 | click | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 6 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 7 | click | linkText=Compila LA |  | 
    await driver.findElement(By.linkText("Compila LA")).click()
    // 8 | click | css=.form-label-group:nth-child(2) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(2) > label")).click()
    // 9 | type | id=inputName | Danny | 
    await driver.findElement(By.id("inputName")).sendKeys("Danny")
    // 10 | type | id=inputSurname | DeVito | 
    await driver.findElement(By.id("inputSurname")).sendKeys("DeVito")
    // 11 | type | id=inputDate | 0001-08-10 | 
    await driver.findElement(By.id("inputDate")).sendKeys("0001-08-10")
    // 12 | type | id=inputDate | 0019-08-10 | 
    await driver.findElement(By.id("inputDate")).sendKeys("0019-08-10")
    // 13 | type | id=inputDate | 0199-08-10 | 
    await driver.findElement(By.id("inputDate")).sendKeys("0199-08-10")
    // 14 | type | id=inputDate | 1997-08-10 | 
    await driver.findElement(By.id("inputDate")).sendKeys("1997-08-10")
    // 15 | click | css=.form-label-group:nth-child(5) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(5) > label")).click()
    // 16 | type | id=inputTelephone | 3335678923 | 
    await driver.findElement(By.id("inputTelephone")).sendKeys("3335678923")
    // 17 | click | id=M |  | 
    await driver.findElement(By.id("M")).click()
    // 18 | click | css=.form-label-group:nth-child(7) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(7) > label")).click()
    // 19 | type | id=nationality | Italiana | 
    await driver.findElement(By.id("nationality")).sendKeys("Italiana")
    // 20 | click | id=1st |  | 
    await driver.findElement(By.id("1st")).click()
    // 21 | click | css=.form-label-group:nth-child(9) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(9) > label")).click()
    // 22 | type | id=inputAcademicYear1 | 19 | 
    await driver.findElement(By.id("inputAcademicYear1")).sendKeys("19")
    // 23 | click | css=.form-label-group:nth-child(10) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(10) > label")).click()
    // 24 | type | id=inputAcademicYear2 | 20 | 
    await driver.findElement(By.id("inputAcademicYear2")).sendKeys("20")
    // 25 | click | css=.form-label-group:nth-child(11) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(11) > label")).click()
    // 26 | type | id=inputSubjectCode | Informatica, 05121 | 
    await driver.findElement(By.id("inputSubjectCode")).sendKeys("Informatica, 05121")
    // 27 | click | css=.form-label-group:nth-child(12) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(12) > label")).click()
    // 28 | type | id=inputEmail | d.de | 
    await driver.findElement(By.id("inputEmail")).sendKeys("d.de")
    // 29 | type | id=inputEmail | d.devito@studenti.unisa.it | 
    await driver.findElement(By.id("inputEmail")).sendKeys("d.devito@studenti.unisa.it")
    // 30 | type | id=inputDepartmentSending | Informatica | 
    await driver.findElement(By.id("inputDepartmentSending")).sendKeys("Informatica")
    // 31 | click | css=.form-label-group:nth-child(17) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(17) > label")).click()
    // 32 | type | id=inputContactName | Paola Penna | 
    await driver.findElement(By.id("inputContactName")).sendKeys("Paola Penna")
    // 33 | click | css=.form-label-group:nth-child(18) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(18) > label")).click()
    // 34 | type | id=inputContactSending | p.penna@unisa.it 167543290 | 
    await driver.findElement(By.id("inputContactSending")).sendKeys("p.penna@unisa.it 167543290")
    // 35 | click | css=.form-label-group:nth-child(22) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(22) > label")).click()
    // 36 | type | id=inputNameSector | Cyber Securuty | 
    await driver.findElement(By.id("inputNameSector")).sendKeys("Cyber Securuty")
    // 37 | click | css=.form-label-group:nth-child(23) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(23) > label")).click()
    // 38 | type | id=inputDepartmentReciving | Hackaton | 
    await driver.findElement(By.id("inputDepartmentReciving")).sendKeys("Hackaton")
    // 39 | click | css=.form-label-group:nth-child(24) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(24) > label")).click()
    // 40 | type | id=inputAddress | Via traviano | 
    await driver.findElement(By.id("inputAddress")).sendKeys("Via traviano")
    // 41 | click | css=.form-label-group:nth-child(25) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(25) > label")).click()
    // 42 | type | id=inputWebSite | www.cybersecurity.it | 
    await driver.findElement(By.id("inputWebSite")).sendKeys("www.cybersecurity.it")
    // 43 | click | id=inlineFormCustomSelect |  | 
    await driver.findElement(By.id("inlineFormCustomSelect")).click()
    // 44 | select | id=inlineFormCustomSelect | label=Italia | 
    {
      const dropdown = await driver.findElement(By.id("inlineFormCustomSelect"))
      await dropdown.findElement(By.xpath("//option[. = 'Italia']")).click()
    }
    // 45 | click | id=inlineFormCustomSelect |  | 
    await driver.findElement(By.id("inlineFormCustomSelect")).click()
    // 46 | click | css=.form-label-group:nth-child(27) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(27) > label")).click()
    // 47 | type | id=inputSizeEnterprise | 150 | 
    await driver.findElement(By.id("inputSizeEnterprise")).sendKeys("150")
    // 48 | click | css=.form-label-group:nth-child(28) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(28) > label")).click()
    // 49 | type | id=inputContactRecivingName | Paola Penna | 
    await driver.findElement(By.id("inputContactRecivingName")).sendKeys("Paola Penna")
    // 50 | click | css=.form-label-group:nth-child(29) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(29) > label")).click()
    // 51 | type | id=inputContactRecivingPosition | Unisa | 
    await driver.findElement(By.id("inputContactRecivingPosition")).sendKeys("Unisa")
    // 52 | click | css=.form-label-group:nth-child(30) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(30) > label")).click()
    // 53 | type | id=inputMentorName | Sara Cotto | 
    await driver.findElement(By.id("inputMentorName")).sendKeys("Sara Cotto")
    // 54 | click | css=.form-label-group:nth-child(31) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(31) > label")).click()
    // 55 | type | id=inputMentorPosition | California | 
    await driver.findElement(By.id("inputMentorPosition")).sendKeys("California")
    // 56 | click | css=.form-label-group:nth-child(32) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(32) > label")).click()
    // 57 | type | id=inputMentorInfo | s.cotto@gmail.com 3324578124 | 
    await driver.findElement(By.id("inputMentorInfo")).sendKeys("s.cotto@gmail.com 3324578124")
    // 58 | click | css=.form-label-group:nth-child(37) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(37) > label")).click()
    // 59 | type | id=inputDateFrom | 10/2019 | 
    await driver.findElement(By.id("inputDateFrom")).sendKeys("10/2019")
    // 60 | click | css=.form-label-group:nth-child(39) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(39) > label")).click()
    // 61 | type | id=inputDateTo | 04/2020 | 
    await driver.findElement(By.id("inputDateTo")).sendKeys("04/2020")
    // 62 | click | id=inputHourWork |  | 
    await driver.findElement(By.id("inputHourWork")).click()
    // 63 | type | id=inputHourWork | 32 | 
    await driver.findElement(By.id("inputHourWork")).sendKeys("32")
    // 64 | click | css=.form-label-group:nth-child(44) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(44) > label")).click()
    // 65 | type | id=inputTitle | Cyber Security | 
    await driver.findElement(By.id("inputTitle")).sendKeys("Cyber Security")
    // 66 | click | css=.form-label-group:nth-child(47) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(47) > label")).click()
    // 67 | type | id=inputDetailed | Sviluppo della sicurezza informatica | 
    await driver.findElement(By.id("inputDetailed")).sendKeys("Sviluppo della sicurezza informatica")
    // 68 | click | css=.form-label-group:nth-child(50) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(50) > label")).click()
    // 69 | type | id=inputKnowledge | Java, python e sicurezza | 
    await driver.findElement(By.id("inputKnowledge")).sendKeys("Java, python e sicurezza")
    // 70 | click | css=.form-label-group:nth-child(53) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(53) > label")).click()
    // 71 | type | id=inputMonitoring | Gestione progettuale | 
    await driver.findElement(By.id("inputMonitoring")).sendKeys("Gestione progettuale")
    // 72 | click | css=.form-label-group:nth-child(56) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(56) > label")).click()
    // 73 | type | id=inputEvaluation | Valutazione progetto finale | 
    await driver.findElement(By.id("inputEvaluation")).sendKeys("Valutazione progetto finale")
    // 74 | click | id=inputLenguage |  | 
    await driver.findElement(By.id("inputLenguage")).click()
    // 75 | select | id=inputLenguage | label=Inglese | 
    {
      const dropdown = await driver.findElement(By.id("inputLenguage"))
      await dropdown.findElement(By.xpath("//option[. = 'Inglese']")).click()
    }
    // 76 | click | id=inputLenguage |  | 
    await driver.findElement(By.id("inputLenguage")).click()
    // 77 | click | id=C1 |  | 
    await driver.findElement(By.id("C1")).click()
    // 78 | click | id=send |  | 
    await driver.findElement(By.id("send")).click()
    // 79 | open | http://localhost:8080/logout |  | 
    await driver.get("http://localhost:8080/logout")
    // 80 | pause | 5000 |  | 
    await driver.sleep(5000)
    // 81 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 82 | click | css=.form-label-group:nth-child(1) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(1) > label")).click()
    // 83 | type | id=inputUsername | p.penna@unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("p.penna@unisa.it")
    // 84 | type | id=inputPassword | PenPaola1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("PenPaola1")
    // 85 | click | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 86 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 87 | click | css=.nav-item:nth-child(2) p |  | 
    await driver.findElement(By.css(".nav-item:nth-child(2) p")).click()
    // 88 | click | linkText=Visualizza |  | 
    await driver.findElement(By.linkText("Visualizza")).click()
    // 89 | click | id=disapprove |  | 
    await driver.findElement(By.id("disapprove")).click()
    // 90 | click | name=msg |  | 
    await driver.findElement(By.name("msg")).click()
    // 91 | type | name=msg | Non mi piace | 
    await driver.findElement(By.name("msg")).sendKeys("Non mi piace")
    // 92 | click | css=.btn-block:nth-child(2) |  | 
    await driver.findElement(By.css(".btn-block:nth-child(2)")).click()
    // 93 | close |  |  | 
    await driver.close()
  })
  it('View Profile', async function() {
    // Test name: View Profile
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    await driver.get("http://localhost:8080/")
    // 2 | setWindowSize | 1600x866 |  | 
    await driver.manage().window().setRect(1600, 866)
    // 3 | type | id=inputUsername | p.penna@unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("p.penna@unisa.it")
    // 4 | type | id=inputPassword | PenPaola1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("PenPaola1")
    // 5 | click | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 6 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 7 | click | id=profile |  | 
    await driver.findElement(By.id("profile")).click()
    // 8 | close |  |  | 
    await driver.close()
  })
  it('View Request Document and View CV', async function() {
    // Test name: View Request Document and View CV
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    await driver.get("http://localhost:8080/")
    // 2 | setWindowSize | 1600x866 |  | 
    await driver.manage().window().setRect(1600, 866)
    // 3 | type | id=inputUsername | l.deamicis@studenti.unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("l.deamicis@studenti.unisa.it")
    // 4 | type | id=inputPassword | DeLorenzo1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("DeLorenzo1")
    // 5 | click | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 6 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 7 | click | linkText=Compila LA |  | 
    await driver.findElement(By.linkText("Compila LA")).click()
    // 8 | click | css=.form-label-group:nth-child(2) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(2) > label")).click()
    // 9 | type | id=inputName | Lorenzo | 
    await driver.findElement(By.id("inputName")).sendKeys("Lorenzo")
    // 10 | type | id=inputSurname | Amicis | 
    await driver.findElement(By.id("inputSurname")).sendKeys("Amicis")
    // 11 | type | id=inputDate | 0001-08-10 | 
    await driver.findElement(By.id("inputDate")).sendKeys("0001-08-10")
    // 12 | type | id=inputDate | 0019-08-10 | 
    await driver.findElement(By.id("inputDate")).sendKeys("0019-08-10")
    // 13 | type | id=inputDate | 0199-08-10 | 
    await driver.findElement(By.id("inputDate")).sendKeys("0199-08-10")
    // 14 | type | id=inputDate | 1997-08-10 | 
    await driver.findElement(By.id("inputDate")).sendKeys("1997-08-10")
    // 15 | click | css=.form-label-group:nth-child(5) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(5) > label")).click()
    // 16 | type | id=inputTelephone | 3335678923 | 
    await driver.findElement(By.id("inputTelephone")).sendKeys("3335678923")
    // 17 | click | id=M |  | 
    await driver.findElement(By.id("M")).click()
    // 18 | click | css=.form-label-group:nth-child(7) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(7) > label")).click()
    // 19 | type | id=nationality | Italiana | 
    await driver.findElement(By.id("nationality")).sendKeys("Italiana")
    // 20 | click | id=1st |  | 
    await driver.findElement(By.id("1st")).click()
    // 21 | click | css=.form-label-group:nth-child(9) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(9) > label")).click()
    // 22 | type | id=inputAcademicYear1 | 19 | 
    await driver.findElement(By.id("inputAcademicYear1")).sendKeys("19")
    // 23 | click | css=.form-label-group:nth-child(10) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(10) > label")).click()
    // 24 | type | id=inputAcademicYear2 | 20 | 
    await driver.findElement(By.id("inputAcademicYear2")).sendKeys("20")
    // 25 | click | css=.form-label-group:nth-child(11) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(11) > label")).click()
    // 26 | type | id=inputSubjectCode | Informatica, 05121 | 
    await driver.findElement(By.id("inputSubjectCode")).sendKeys("Informatica, 05121")
    // 27 | click | css=.form-label-group:nth-child(12) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(12) > label")).click()
    // 28 | type | id=inputEmail | l.deamicis@studenti.unisa.it | 
    await driver.findElement(By.id("inputEmail")).sendKeys("l.deamicis@studenti.unisa.it")
    // 29 | type | id=inputDepartmentSending | Informatica | 
    await driver.findElement(By.id("inputDepartmentSending")).sendKeys("Informatica")
    // 30 | click | css=.form-label-group:nth-child(17) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(17) > label")).click()
    // 31 | type | id=inputContactName | Paola Penna | 
    await driver.findElement(By.id("inputContactName")).sendKeys("Paola Penna")
    // 32 | click | css=.form-label-group:nth-child(18) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(18) > label")).click()
    // 33 | type | id=inputContactSending | p.penna@unisa.it 167543290 | 
    await driver.findElement(By.id("inputContactSending")).sendKeys("p.penna@unisa.it 167543290")
    // 34 | click | css=.form-label-group:nth-child(22) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(22) > label")).click()
    // 35 | type | id=inputNameSector | Cyber Securuty | 
    await driver.findElement(By.id("inputNameSector")).sendKeys("Cyber Securuty")
    // 36 | click | css=.form-label-group:nth-child(23) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(23) > label")).click()
    // 37 | type | id=inputDepartmentReciving | Hackaton | 
    await driver.findElement(By.id("inputDepartmentReciving")).sendKeys("Hackaton")
    // 38 | click | css=.form-label-group:nth-child(24) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(24) > label")).click()
    // 39 | type | id=inputAddress | Via traviano | 
    await driver.findElement(By.id("inputAddress")).sendKeys("Via traviano")
    // 40 | click | css=.form-label-group:nth-child(25) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(25) > label")).click()
    // 41 | type | id=inputWebSite | www.cybersecurity.it | 
    await driver.findElement(By.id("inputWebSite")).sendKeys("www.cybersecurity.it")
    // 42 | click | id=inlineFormCustomSelect |  | 
    await driver.findElement(By.id("inlineFormCustomSelect")).click()
    // 43 | select | id=inlineFormCustomSelect | label=Italia | 
    {
      const dropdown = await driver.findElement(By.id("inlineFormCustomSelect"))
      await dropdown.findElement(By.xpath("//option[. = 'Italia']")).click()
    }
    // 44 | click | id=inlineFormCustomSelect |  | 
    await driver.findElement(By.id("inlineFormCustomSelect")).click()
    // 45 | click | css=.form-label-group:nth-child(27) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(27) > label")).click()
    // 46 | type | id=inputSizeEnterprise | 150 | 
    await driver.findElement(By.id("inputSizeEnterprise")).sendKeys("150")
    // 47 | click | css=.form-label-group:nth-child(28) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(28) > label")).click()
    // 48 | type | id=inputContactRecivingName | Paola Penna | 
    await driver.findElement(By.id("inputContactRecivingName")).sendKeys("Paola Penna")
    // 49 | click | css=.form-label-group:nth-child(29) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(29) > label")).click()
    // 50 | type | id=inputContactRecivingPosition | Unisa | 
    await driver.findElement(By.id("inputContactRecivingPosition")).sendKeys("Unisa")
    // 51 | click | css=.form-label-group:nth-child(30) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(30) > label")).click()
    // 52 | type | id=inputMentorName | Sara Cotto | 
    await driver.findElement(By.id("inputMentorName")).sendKeys("Sara Cotto")
    // 53 | click | css=.form-label-group:nth-child(31) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(31) > label")).click()
    // 54 | type | id=inputMentorPosition | California | 
    await driver.findElement(By.id("inputMentorPosition")).sendKeys("California")
    // 55 | click | css=.form-label-group:nth-child(32) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(32) > label")).click()
    // 56 | type | id=inputMentorInfo | s.cotto@gmail.com 3324578124 | 
    await driver.findElement(By.id("inputMentorInfo")).sendKeys("s.cotto@gmail.com 3324578124")
    // 57 | click | css=.form-label-group:nth-child(37) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(37) > label")).click()
    // 58 | type | id=inputDateFrom | 10/2019 | 
    await driver.findElement(By.id("inputDateFrom")).sendKeys("10/2019")
    // 59 | click | css=.form-label-group:nth-child(39) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(39) > label")).click()
    // 60 | type | id=inputDateTo | 04/2020 | 
    await driver.findElement(By.id("inputDateTo")).sendKeys("04/2020")
    // 61 | click | id=inputHourWork |  | 
    await driver.findElement(By.id("inputHourWork")).click()
    // 62 | type | id=inputHourWork | 32 | 
    await driver.findElement(By.id("inputHourWork")).sendKeys("32")
    // 63 | click | css=.form-label-group:nth-child(44) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(44) > label")).click()
    // 64 | type | id=inputTitle | Cyber Security | 
    await driver.findElement(By.id("inputTitle")).sendKeys("Cyber Security")
    // 65 | click | css=.form-label-group:nth-child(47) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(47) > label")).click()
    // 66 | type | id=inputDetailed | Sviluppo della sicurezza informatica | 
    await driver.findElement(By.id("inputDetailed")).sendKeys("Sviluppo della sicurezza informatica")
    // 67 | click | css=.form-label-group:nth-child(50) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(50) > label")).click()
    // 68 | type | id=inputKnowledge | Java, python e sicurezza | 
    await driver.findElement(By.id("inputKnowledge")).sendKeys("Java, python e sicurezza")
    // 69 | click | css=.form-label-group:nth-child(53) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(53) > label")).click()
    // 70 | type | id=inputMonitoring | Gestione progettuale | 
    await driver.findElement(By.id("inputMonitoring")).sendKeys("Gestione progettuale")
    // 71 | click | css=.form-label-group:nth-child(56) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(56) > label")).click()
    // 72 | type | id=inputEvaluation | Valutazione progetto finale | 
    await driver.findElement(By.id("inputEvaluation")).sendKeys("Valutazione progetto finale")
    // 73 | click | id=inputLenguage |  | 
    await driver.findElement(By.id("inputLenguage")).click()
    // 74 | select | id=inputLenguage | label=Inglese | 
    {
      const dropdown = await driver.findElement(By.id("inputLenguage"))
      await dropdown.findElement(By.xpath("//option[. = 'Inglese']")).click()
    }
    // 75 | click | id=inputLenguage |  | 
    await driver.findElement(By.id("inputLenguage")).click()
    // 76 | click | id=C1 |  | 
    await driver.findElement(By.id("C1")).click()
    // 77 | click | id=send |  | 
    await driver.findElement(By.id("send")).click()
    // 78 | open | http://localhost:8080/logout |  | 
    await driver.get("http://localhost:8080/logout")
    // 79 | pause | 5000 |  | 
    await driver.sleep(5000)
    // 80 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 81 | click | css=.form-label-group:nth-child(1) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(1) > label")).click()
    // 82 | type | id=inputUsername | p.penna@unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("p.penna@unisa.it")
    // 83 | type | id=inputPassword | PenPaola1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("PenPaola1")
    // 84 | click | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 85 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 86 | click | css=.nav-item:nth-child(2) p |  | 
    await driver.findElement(By.css(".nav-item:nth-child(2) p")).click()
    // 87 | click | linkText=Visualizza |  | 
    await driver.findElement(By.linkText("Visualizza")).click()
    // 88 | click | id=cv |  | 
    await driver.findElement(By.id("cv")).click()
    // 89 | pause | 3000 |  | 
    await driver.sleep(3000)
    // 90 | close |  |  | 
    await driver.close()
  })
  it('View Request Document and View ID', async function() {
    // Test name: View Request Document and View ID
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    await driver.get("http://localhost:8080/")
    // 2 | setWindowSize | 1600x866 |  | 
    await driver.manage().window().setRect(1600, 866)
    // 3 | type | id=inputUsername | d.marino@studenti.unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("d.marino@studenti.unisa.it")
    // 4 | type | id=inputPassword | MarDomenico1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("MarDomenico1")
    // 5 | click | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 6 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 7 | click | linkText=Compila LA |  | 
    await driver.findElement(By.linkText("Compila LA")).click()
    // 8 | click | css=.form-label-group:nth-child(2) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(2) > label")).click()
    // 9 | type | id=inputName | Domenico | 
    await driver.findElement(By.id("inputName")).sendKeys("Domenico")
    // 10 | type | id=inputSurname | Marino | 
    await driver.findElement(By.id("inputSurname")).sendKeys("Marino")
    // 11 | type | id=inputDate | 0001-08-10 | 
    await driver.findElement(By.id("inputDate")).sendKeys("0001-08-10")
    // 12 | type | id=inputDate | 0019-08-10 | 
    await driver.findElement(By.id("inputDate")).sendKeys("0019-08-10")
    // 13 | type | id=inputDate | 0199-08-10 | 
    await driver.findElement(By.id("inputDate")).sendKeys("0199-08-10")
    // 14 | type | id=inputDate | 1997-08-10 | 
    await driver.findElement(By.id("inputDate")).sendKeys("1997-08-10")
    // 15 | click | css=.form-label-group:nth-child(5) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(5) > label")).click()
    // 16 | type | id=inputTelephone | 3335678923 | 
    await driver.findElement(By.id("inputTelephone")).sendKeys("3335678923")
    // 17 | click | id=M |  | 
    await driver.findElement(By.id("M")).click()
    // 18 | click | css=.form-label-group:nth-child(7) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(7) > label")).click()
    // 19 | type | id=nationality | Italiana | 
    await driver.findElement(By.id("nationality")).sendKeys("Italiana")
    // 20 | click | id=1st |  | 
    await driver.findElement(By.id("1st")).click()
    // 21 | click | css=.form-label-group:nth-child(9) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(9) > label")).click()
    // 22 | type | id=inputAcademicYear1 | 19 | 
    await driver.findElement(By.id("inputAcademicYear1")).sendKeys("19")
    // 23 | click | css=.form-label-group:nth-child(10) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(10) > label")).click()
    // 24 | type | id=inputAcademicYear2 | 20 | 
    await driver.findElement(By.id("inputAcademicYear2")).sendKeys("20")
    // 25 | click | css=.form-label-group:nth-child(11) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(11) > label")).click()
    // 26 | type | id=inputSubjectCode | Informatica, 05121 | 
    await driver.findElement(By.id("inputSubjectCode")).sendKeys("Informatica, 05121")
    // 27 | click | css=.form-label-group:nth-child(12) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(12) > label")).click()
    // 28 | type | id=inputEmail | d.marino@studenti.unisa.it | 
    await driver.findElement(By.id("inputEmail")).sendKeys("d.marino@studenti.unisa.it")
    // 29 | type | id=inputDepartmentSending | Informatica | 
    await driver.findElement(By.id("inputDepartmentSending")).sendKeys("Informatica")
    // 30 | click | css=.form-label-group:nth-child(17) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(17) > label")).click()
    // 31 | type | id=inputContactName | Paola Penna | 
    await driver.findElement(By.id("inputContactName")).sendKeys("Paola Penna")
    // 32 | click | css=.form-label-group:nth-child(18) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(18) > label")).click()
    // 33 | type | id=inputContactSending | p.penna@unisa.it 167543290 | 
    await driver.findElement(By.id("inputContactSending")).sendKeys("p.penna@unisa.it 167543290")
    // 34 | click | css=.form-label-group:nth-child(22) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(22) > label")).click()
    // 35 | type | id=inputNameSector | Cyber Securuty | 
    await driver.findElement(By.id("inputNameSector")).sendKeys("Cyber Securuty")
    // 36 | click | css=.form-label-group:nth-child(23) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(23) > label")).click()
    // 37 | type | id=inputDepartmentReciving | Hackaton | 
    await driver.findElement(By.id("inputDepartmentReciving")).sendKeys("Hackaton")
    // 38 | click | css=.form-label-group:nth-child(24) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(24) > label")).click()
    // 39 | type | id=inputAddress | Via traviano | 
    await driver.findElement(By.id("inputAddress")).sendKeys("Via traviano")
    // 40 | click | css=.form-label-group:nth-child(25) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(25) > label")).click()
    // 41 | type | id=inputWebSite | www.cybersecurity.it | 
    await driver.findElement(By.id("inputWebSite")).sendKeys("www.cybersecurity.it")
    // 42 | click | id=inlineFormCustomSelect |  | 
    await driver.findElement(By.id("inlineFormCustomSelect")).click()
    // 43 | select | id=inlineFormCustomSelect | label=Italia | 
    {
      const dropdown = await driver.findElement(By.id("inlineFormCustomSelect"))
      await dropdown.findElement(By.xpath("//option[. = 'Italia']")).click()
    }
    // 44 | click | id=inlineFormCustomSelect |  | 
    await driver.findElement(By.id("inlineFormCustomSelect")).click()
    // 45 | click | css=.form-label-group:nth-child(27) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(27) > label")).click()
    // 46 | type | id=inputSizeEnterprise | 150 | 
    await driver.findElement(By.id("inputSizeEnterprise")).sendKeys("150")
    // 47 | click | css=.form-label-group:nth-child(28) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(28) > label")).click()
    // 48 | type | id=inputContactRecivingName | Paola Penna | 
    await driver.findElement(By.id("inputContactRecivingName")).sendKeys("Paola Penna")
    // 49 | click | css=.form-label-group:nth-child(29) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(29) > label")).click()
    // 50 | type | id=inputContactRecivingPosition | Unisa | 
    await driver.findElement(By.id("inputContactRecivingPosition")).sendKeys("Unisa")
    // 51 | click | css=.form-label-group:nth-child(30) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(30) > label")).click()
    // 52 | type | id=inputMentorName | Sara Cotto | 
    await driver.findElement(By.id("inputMentorName")).sendKeys("Sara Cotto")
    // 53 | click | css=.form-label-group:nth-child(31) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(31) > label")).click()
    // 54 | type | id=inputMentorPosition | California | 
    await driver.findElement(By.id("inputMentorPosition")).sendKeys("California")
    // 55 | click | css=.form-label-group:nth-child(32) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(32) > label")).click()
    // 56 | type | id=inputMentorInfo | s.cotto@gmail.com 3324578124 | 
    await driver.findElement(By.id("inputMentorInfo")).sendKeys("s.cotto@gmail.com 3324578124")
    // 57 | click | css=.form-label-group:nth-child(37) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(37) > label")).click()
    // 58 | type | id=inputDateFrom | 10/2019 | 
    await driver.findElement(By.id("inputDateFrom")).sendKeys("10/2019")
    // 59 | click | css=.form-label-group:nth-child(39) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(39) > label")).click()
    // 60 | type | id=inputDateTo | 04/2020 | 
    await driver.findElement(By.id("inputDateTo")).sendKeys("04/2020")
    // 61 | click | id=inputHourWork |  | 
    await driver.findElement(By.id("inputHourWork")).click()
    // 62 | type | id=inputHourWork | 32 | 
    await driver.findElement(By.id("inputHourWork")).sendKeys("32")
    // 63 | click | css=.form-label-group:nth-child(44) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(44) > label")).click()
    // 64 | type | id=inputTitle | Cyber Security | 
    await driver.findElement(By.id("inputTitle")).sendKeys("Cyber Security")
    // 65 | click | css=.form-label-group:nth-child(47) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(47) > label")).click()
    // 66 | type | id=inputDetailed | Sviluppo della sicurezza informatica | 
    await driver.findElement(By.id("inputDetailed")).sendKeys("Sviluppo della sicurezza informatica")
    // 67 | click | css=.form-label-group:nth-child(50) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(50) > label")).click()
    // 68 | type | id=inputKnowledge | Java, python e sicurezza | 
    await driver.findElement(By.id("inputKnowledge")).sendKeys("Java, python e sicurezza")
    // 69 | click | css=.form-label-group:nth-child(53) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(53) > label")).click()
    // 70 | type | id=inputMonitoring | Gestione progettuale | 
    await driver.findElement(By.id("inputMonitoring")).sendKeys("Gestione progettuale")
    // 71 | click | css=.form-label-group:nth-child(56) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(56) > label")).click()
    // 72 | type | id=inputEvaluation | Valutazione progetto finale | 
    await driver.findElement(By.id("inputEvaluation")).sendKeys("Valutazione progetto finale")
    // 73 | click | id=inputLenguage |  | 
    await driver.findElement(By.id("inputLenguage")).click()
    // 74 | select | id=inputLenguage | label=Inglese | 
    {
      const dropdown = await driver.findElement(By.id("inputLenguage"))
      await dropdown.findElement(By.xpath("//option[. = 'Inglese']")).click()
    }
    // 75 | click | id=inputLenguage |  | 
    await driver.findElement(By.id("inputLenguage")).click()
    // 76 | click | id=C1 |  | 
    await driver.findElement(By.id("C1")).click()
    // 77 | click | id=send |  | 
    await driver.findElement(By.id("send")).click()
    // 78 | open | http://localhost:8080/logout |  | 
    await driver.get("http://localhost:8080/logout")
    // 79 | pause | 5000 |  | 
    await driver.sleep(5000)
    // 80 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 81 | click | css=.form-label-group:nth-child(1) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(1) > label")).click()
    // 82 | type | id=inputUsername | p.penna@unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("p.penna@unisa.it")
    // 83 | type | id=inputPassword | PenPaola1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("PenPaola1")
    // 84 | click | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 85 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 86 | click | css=.nav-item:nth-child(2) p |  | 
    await driver.findElement(By.css(".nav-item:nth-child(2) p")).click()
    // 87 | click | linkText=Visualizza |  | 
    await driver.findElement(By.linkText("Visualizza")).click()
    // 88 | click | id=id |  | 
    await driver.findElement(By.id("id")).click()
    // 89 | pause | 3000 |  | 
    await driver.sleep(3000)
    // 90 | close |  |  | 
    await driver.close()
  })
  it('View Request List', async function() {
    // Test name: View Request List
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    await driver.get("http://localhost:8080/")
    // 2 | setWindowSize | 1600x866 |  | 
    await driver.manage().window().setRect(1600, 866)
    // 3 | type | id=inputUsername | p.penna@unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("p.penna@unisa.it")
    // 4 | type | id=inputPassword | PenPaola1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("PenPaola1")
    // 5 | sendKeys | id=inputPassword | ${KEY_ENTER} | 
    await driver.findElement(By.id("inputPassword")).sendKeys(Key.ENTER)
    // 6 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 7 | click | css=.nav-item:nth-child(2) p |  | 
    await driver.findElement(By.css(".nav-item:nth-child(2) p")).click()
    // 8 | close |  |  | 
    await driver.close()
  })
  it('View Request, Approve and Delete Notification', async function() {
    // Test name: View Request, Approve and Delete Notification
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    await driver.get("http://localhost:8080/")
    // 2 | setWindowSize | 1600x866 |  | 
    await driver.manage().window().setRect(1600, 866)
    // 3 | type | id=inputUsername | f.vitolo@studenti.unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("f.vitolo@studenti.unisa.it")
    // 4 | type | id=inputPassword | VitoFerdi1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("VitoFerdi1")
    // 5 | click | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 6 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 7 | click | linkText=Compila LA |  | 
    await driver.findElement(By.linkText("Compila LA")).click()
    // 8 | click | css=.form-label-group:nth-child(2) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(2) > label")).click()
    // 9 | type | id=inputName | Fernando | 
    await driver.findElement(By.id("inputName")).sendKeys("Fernando")
    // 10 | type | id=inputSurname | Vitolo | 
    await driver.findElement(By.id("inputSurname")).sendKeys("Vitolo")
    // 11 | type | id=inputDate | 0001-08-10 | 
    await driver.findElement(By.id("inputDate")).sendKeys("0001-08-10")
    // 12 | type | id=inputDate | 0019-08-10 | 
    await driver.findElement(By.id("inputDate")).sendKeys("0019-08-10")
    // 13 | type | id=inputDate | 0199-08-10 | 
    await driver.findElement(By.id("inputDate")).sendKeys("0199-08-10")
    // 14 | type | id=inputDate | 1997-08-10 | 
    await driver.findElement(By.id("inputDate")).sendKeys("1997-08-10")
    // 15 | click | css=.form-label-group:nth-child(5) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(5) > label")).click()
    // 16 | type | id=inputTelephone | 3335678923 | 
    await driver.findElement(By.id("inputTelephone")).sendKeys("3335678923")
    // 17 | click | id=M |  | 
    await driver.findElement(By.id("M")).click()
    // 18 | click | css=.form-label-group:nth-child(7) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(7) > label")).click()
    // 19 | type | id=nationality | Italiana | 
    await driver.findElement(By.id("nationality")).sendKeys("Italiana")
    // 20 | click | id=1st |  | 
    await driver.findElement(By.id("1st")).click()
    // 21 | click | css=.form-label-group:nth-child(9) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(9) > label")).click()
    // 22 | type | id=inputAcademicYear1 | 19 | 
    await driver.findElement(By.id("inputAcademicYear1")).sendKeys("19")
    // 23 | click | css=.form-label-group:nth-child(10) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(10) > label")).click()
    // 24 | type | id=inputAcademicYear2 | 20 | 
    await driver.findElement(By.id("inputAcademicYear2")).sendKeys("20")
    // 25 | click | css=.form-label-group:nth-child(11) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(11) > label")).click()
    // 26 | type | id=inputSubjectCode | Informatica, 05121 | 
    await driver.findElement(By.id("inputSubjectCode")).sendKeys("Informatica, 05121")
    // 27 | click | css=.form-label-group:nth-child(12) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(12) > label")).click()
    // 28 | type | id=inputEmail | f.vitolo@studenti.unisa.it | 
    await driver.findElement(By.id("inputEmail")).sendKeys("f.vitolo@studenti.unisa.it")
    // 29 | type | id=inputDepartmentSending | Informatica | 
    await driver.findElement(By.id("inputDepartmentSending")).sendKeys("Informatica")
    // 30 | click | css=.form-label-group:nth-child(17) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(17) > label")).click()
    // 31 | type | id=inputContactName | Paola Penna | 
    await driver.findElement(By.id("inputContactName")).sendKeys("Paola Penna")
    // 32 | click | css=.form-label-group:nth-child(18) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(18) > label")).click()
    // 33 | type | id=inputContactSending | p.penna@unisa.it 167543290 | 
    await driver.findElement(By.id("inputContactSending")).sendKeys("p.penna@unisa.it 167543290")
    // 34 | click | css=.form-label-group:nth-child(22) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(22) > label")).click()
    // 35 | type | id=inputNameSector | Cyber Securuty | 
    await driver.findElement(By.id("inputNameSector")).sendKeys("Cyber Securuty")
    // 36 | click | css=.form-label-group:nth-child(23) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(23) > label")).click()
    // 37 | type | id=inputDepartmentReciving | Hackaton | 
    await driver.findElement(By.id("inputDepartmentReciving")).sendKeys("Hackaton")
    // 38 | click | css=.form-label-group:nth-child(24) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(24) > label")).click()
    // 39 | type | id=inputAddress | Via traviano | 
    await driver.findElement(By.id("inputAddress")).sendKeys("Via traviano")
    // 40 | click | css=.form-label-group:nth-child(25) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(25) > label")).click()
    // 41 | type | id=inputWebSite | www.cybersecurity.it | 
    await driver.findElement(By.id("inputWebSite")).sendKeys("www.cybersecurity.it")
    // 42 | click | id=inlineFormCustomSelect |  | 
    await driver.findElement(By.id("inlineFormCustomSelect")).click()
    // 43 | select | id=inlineFormCustomSelect | label=Italia | 
    {
      const dropdown = await driver.findElement(By.id("inlineFormCustomSelect"))
      await dropdown.findElement(By.xpath("//option[. = 'Italia']")).click()
    }
    // 44 | click | id=inlineFormCustomSelect |  | 
    await driver.findElement(By.id("inlineFormCustomSelect")).click()
    // 45 | click | css=.form-label-group:nth-child(27) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(27) > label")).click()
    // 46 | type | id=inputSizeEnterprise | 150 | 
    await driver.findElement(By.id("inputSizeEnterprise")).sendKeys("150")
    // 47 | click | css=.form-label-group:nth-child(28) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(28) > label")).click()
    // 48 | type | id=inputContactRecivingName | Paola Penna | 
    await driver.findElement(By.id("inputContactRecivingName")).sendKeys("Paola Penna")
    // 49 | click | css=.form-label-group:nth-child(29) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(29) > label")).click()
    // 50 | type | id=inputContactRecivingPosition | Unisa | 
    await driver.findElement(By.id("inputContactRecivingPosition")).sendKeys("Unisa")
    // 51 | click | css=.form-label-group:nth-child(30) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(30) > label")).click()
    // 52 | type | id=inputMentorName | Sara Cotto | 
    await driver.findElement(By.id("inputMentorName")).sendKeys("Sara Cotto")
    // 53 | click | css=.form-label-group:nth-child(31) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(31) > label")).click()
    // 54 | type | id=inputMentorPosition | California | 
    await driver.findElement(By.id("inputMentorPosition")).sendKeys("California")
    // 55 | click | css=.form-label-group:nth-child(32) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(32) > label")).click()
    // 56 | type | id=inputMentorInfo | s.cotto@gmail.com 3324578124 | 
    await driver.findElement(By.id("inputMentorInfo")).sendKeys("s.cotto@gmail.com 3324578124")
    // 57 | click | css=.form-label-group:nth-child(37) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(37) > label")).click()
    // 58 | type | id=inputDateFrom | 10/2019 | 
    await driver.findElement(By.id("inputDateFrom")).sendKeys("10/2019")
    // 59 | click | css=.form-label-group:nth-child(39) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(39) > label")).click()
    // 60 | type | id=inputDateTo | 04/2020 | 
    await driver.findElement(By.id("inputDateTo")).sendKeys("04/2020")
    // 61 | click | id=inputHourWork |  | 
    await driver.findElement(By.id("inputHourWork")).click()
    // 62 | type | id=inputHourWork | 32 | 
    await driver.findElement(By.id("inputHourWork")).sendKeys("32")
    // 63 | click | css=.form-label-group:nth-child(44) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(44) > label")).click()
    // 64 | type | id=inputTitle | Cyber Security | 
    await driver.findElement(By.id("inputTitle")).sendKeys("Cyber Security")
    // 65 | click | css=.form-label-group:nth-child(47) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(47) > label")).click()
    // 66 | type | id=inputDetailed | Sviluppo della sicurezza informatica | 
    await driver.findElement(By.id("inputDetailed")).sendKeys("Sviluppo della sicurezza informatica")
    // 67 | click | css=.form-label-group:nth-child(50) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(50) > label")).click()
    // 68 | type | id=inputKnowledge | Java, python e sicurezza | 
    await driver.findElement(By.id("inputKnowledge")).sendKeys("Java, python e sicurezza")
    // 69 | click | css=.form-label-group:nth-child(53) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(53) > label")).click()
    // 70 | type | id=inputMonitoring | Gestione progettuale | 
    await driver.findElement(By.id("inputMonitoring")).sendKeys("Gestione progettuale")
    // 71 | click | css=.form-label-group:nth-child(56) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(56) > label")).click()
    // 72 | type | id=inputEvaluation | Valutazione progetto finale | 
    await driver.findElement(By.id("inputEvaluation")).sendKeys("Valutazione progetto finale")
    // 73 | click | id=inputLenguage |  | 
    await driver.findElement(By.id("inputLenguage")).click()
    // 74 | select | id=inputLenguage | label=Inglese | 
    {
      const dropdown = await driver.findElement(By.id("inputLenguage"))
      await dropdown.findElement(By.xpath("//option[. = 'Inglese']")).click()
    }
    // 75 | click | id=inputLenguage |  | 
    await driver.findElement(By.id("inputLenguage")).click()
    // 76 | click | id=C1 |  | 
    await driver.findElement(By.id("C1")).click()
    // 77 | click | id=send |  | 
    await driver.findElement(By.id("send")).click()
    // 78 | open | http://localhost:8080/logout |  | 
    await driver.get("http://localhost:8080/logout")
    // 79 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 80 | click | css=.form-label-group:nth-child(1) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(1) > label")).click()
    // 81 | type | id=inputUsername | p.penna@unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("p.penna@unisa.it")
    // 82 | type | id=inputPassword | PenPaola1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("PenPaola1")
    // 83 | click | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 84 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 85 | click | css=.fa-bell |  | 
    await driver.findElement(By.css(".fa-bell")).click()
    // 86 | mouseOver | css=.speech-bubble |  | 
    {
      const element = await driver.findElement(By.css(".speech-bubble"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 87 | mouseOut | css=.speech-bubble |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 88 | click | id=delete-notification |  | 
    await driver.findElement(By.id("delete-notification")).click()
    // 89 | click | css=.swal-button--confirm |  | 
    await driver.findElement(By.css(".swal-button--confirm")).click()
    // 90 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 91 | click | css=.nav-item:nth-child(2) p |  | 
    await driver.findElement(By.css(".nav-item:nth-child(2) p")).click()
    // 92 | click | linkText=Visualizza |  | 
    await driver.findElement(By.linkText("Visualizza")).click()
    // 93 | click | id=approve1 |  | 
    await driver.findElement(By.id("approve1")).click()
    // 94 | click | id=inputCredits |  | 
    await driver.findElement(By.id("inputCredits")).click()
    // 95 | type | id=inputCredits | 10 | 
    await driver.findElement(By.id("inputCredits")).sendKeys("10")
    // 96 | click | css=li:nth-child(3) > .form-check:nth-child(3) > .form-check-label |  | 
    await driver.findElement(By.css("li:nth-child(3) > .form-check:nth-child(3) > .form-check-label")).click()
    // 97 | click | id=inputInterview |  | 
    await driver.findElement(By.id("inputInterview")).click()
    // 98 | click | xpath=(//input[@id='inputRadio1'])[2] |  | 
    await driver.findElement(By.xpath("(//input[@id=\'inputRadio1\'])[2]")).click()
    // 99 | click | id=send |  | 
    await driver.findElement(By.id("send")).click()
    // 100 | close |  |  | 
    await driver.close()
  })
  it('Chat Message', async function() {
    // Test name: Chat Message
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    await driver.get("http://localhost:8080/")
    // 2 | setWindowSize | 1600x866 |  | 
    await driver.manage().window().setRect(1600, 866)
    // 3 | type | id=inputUsername | p.penna@unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("p.penna@unisa.it")
    // 4 | type | id=inputPassword | PenPaola1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("PenPaola1")
    // 5 | sendKeys | id=inputPassword | ${KEY_ENTER} | 
    await driver.findElement(By.id("inputPassword")).sendKeys(Key.ENTER)
    // 6 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 7 | click | css=.fa-comment |  | 
    await driver.findElement(By.css(".fa-comment")).click()
    // 8 | click | css=.contact-container:nth-child(1) .user-info-name |  | 
    await driver.findElement(By.css(".contact-container:nth-child(1) .user-info-name")).click()
    // 9 | click | id=input-chat |  | 
    await driver.findElement(By.id("input-chat")).click()
    // 10 | type | id=input-chat | heyy | 
    await driver.findElement(By.id("input-chat")).sendKeys("heyy")
    // 11 | click | css=#form-chat > .sendButton |  | 
    await driver.findElement(By.css("#form-chat > .sendButton")).click()
    // 12 | mouseOver | css=#form-chat > .sendButton |  | 
    {
      const element = await driver.findElement(By.css("#form-chat > .sendButton"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 13 | mouseOut | css=#form-chat > .sendButton |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 14 | click | css=.chat-menu |  | 
    await driver.findElement(By.css(".chat-menu")).click()
    // 15 | click | css=.update-message > .button-menu |  | 
    await driver.findElement(By.css(".update-message > .button-menu")).click()
    // 16 | click | id=input-chat |  | 
    await driver.findElement(By.id("input-chat")).click()
    // 17 | type | id=input-chat | hey | 
    await driver.findElement(By.id("input-chat")).sendKeys("hey")
    // 18 | click | css=#form-chat > .sendButton |  | 
    await driver.findElement(By.css("#form-chat > .sendButton")).click()
    // 19 | click | css=.chat-menu |  | 
    await driver.findElement(By.css(".chat-menu")).click()
    // 20 | mouseOver | css=.chat-menu |  | 
    {
      const element = await driver.findElement(By.css(".chat-menu"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 21 | mouseOut | css=.chat-menu |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 22 | click | css=.remove-message > .button-menu |  | 
    await driver.findElement(By.css(".remove-message > .button-menu")).click()
    // 23 | click | css=.swal-button--cancel |  | 
    await driver.findElement(By.css(".swal-button--cancel")).click()
    // 24 | click | css=.chat-menu |  | 
    await driver.findElement(By.css(".chat-menu")).click()
    // 25 | click | css=.remove-message > .button-menu |  | 
    await driver.findElement(By.css(".remove-message > .button-menu")).click()
    // 26 | click | css=.swal-button--confirm |  | 
    await driver.findElement(By.css(".swal-button--confirm")).click()
    // 27 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 28 | click | id=close-chat |  | 
    await driver.findElement(By.id("close-chat")).click()
    // 29 | close |  |  | 
    await driver.close()
  })
  it('Edit Profile', async function() {
    // Test name: Edit Profile
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    await driver.get("http://localhost:8080/")
    // 2 | setWindowSize | 1600x866 |  | 
    await driver.manage().window().setRect(1600, 866)
    // 3 | type | id=inputUsername | p.penna@unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("p.penna@unisa.it")
    // 4 | type | id=inputPassword | PenPaola1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("PenPaola1")
    // 5 | click | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 6 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 7 | click | id=nome |  | 
    await driver.findElement(By.id("nome")).click()
    // 8 | click | css=.btn-secondary:nth-child(2) |  | 
    await driver.findElement(By.css(".btn-secondary:nth-child(2)")).click()
    // 9 | click | id=inputNameAc |  | 
    await driver.findElement(By.id("inputNameAc")).click()
    // 10 | type | id=inputNameAc | Paolina | 
    await driver.findElement(By.id("inputNameAc")).sendKeys("Paolina")
    // 11 | click | css=#formUpdate > .btn |  | 
    await driver.findElement(By.css("#formUpdate > .btn")).click()
    // 12 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 13 | click | css=.btn-secondary:nth-child(2) |  | 
    await driver.findElement(By.css(".btn-secondary:nth-child(2)")).click()
    // 14 | click | id=inputOldPassword |  | 
    await driver.findElement(By.id("inputOldPassword")).click()
    // 15 | type | id=inputOldPassword | PenPaola1 | 
    await driver.findElement(By.id("inputOldPassword")).sendKeys("PenPaola1")
    // 16 | click | id=inputPassword |  | 
    await driver.findElement(By.id("inputPassword")).click()
    // 17 | type | id=inputPassword | ciaociao | 
    await driver.findElement(By.id("inputPassword")).sendKeys("ciaociao")
    // 18 | click | id=inputConfirmPassword |  | 
    await driver.findElement(By.id("inputConfirmPassword")).click()
    // 19 | type | id=inputConfirmPassword | ciaociao | 
    await driver.findElement(By.id("inputConfirmPassword")).sendKeys("ciaociao")
    // 20 | click | css=#formUpdatePass > .btn |  | 
    await driver.findElement(By.css("#formUpdatePass > .btn")).click()
    // 21 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 22 | open | http://localhost:8080/logout |  | 
    await driver.get("http://localhost:8080/logout")
    // 23 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 24 | type | id=inputUsername | p.penna@unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("p.penna@unisa.it")
    // 25 | type | id=inputPassword | ciaociao | 
    await driver.findElement(By.id("inputPassword")).sendKeys("ciaociao")
    // 26 | click | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 27 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 28 | click | id=nome |  | 
    await driver.findElement(By.id("nome")).click()
    // 29 | click | css=.btn-secondary:nth-child(2) |  | 
    await driver.findElement(By.css(".btn-secondary:nth-child(2)")).click()
    // 30 | click | id=inputOldPassword |  | 
    await driver.findElement(By.id("inputOldPassword")).click()
    // 31 | type | id=inputOldPassword | ciaociao | 
    await driver.findElement(By.id("inputOldPassword")).sendKeys("ciaociao")
    // 32 | click | id=inputPassword |  | 
    await driver.findElement(By.id("inputPassword")).click()
    // 33 | type | id=inputPassword | PenPaola1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("PenPaola1")
    // 34 | click | id=inputConfirmPassword |  | 
    await driver.findElement(By.id("inputConfirmPassword")).click()
    // 35 | type | id=inputConfirmPassword | PenPaola1 | 
    await driver.findElement(By.id("inputConfirmPassword")).sendKeys("PenPaola1")
    // 36 | click | css=#formUpdatePass > .btn |  | 
    await driver.findElement(By.css("#formUpdatePass > .btn")).click()
    // 37 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 38 | close |  |  | 
    await driver.close()
  })
  it('Login', async function() {
    // Test name: Login
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    await driver.get("http://localhost:8080/")
    // 2 | setWindowSize | 1600x866 |  | 
    await driver.manage().window().setRect(1600, 866)
    // 3 | type | id=inputUsername | p.penna@unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("p.penna@unisa.it")
    // 4 | type | id=inputPassword | PenPaola1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("PenPaola1")
    // 5 | click | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 6 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 7 | close |  |  | 
    await driver.close()
  })
  it('Logout', async function() {
    // Test name: Logout
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    await driver.get("http://localhost:8080/")
    // 2 | setWindowSize | 1600x866 |  | 
    await driver.manage().window().setRect(1600, 866)
    // 3 | type | id=inputUsername | p.penna@unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("p.penna@unisa.it")
    // 4 | type | id=inputPassword | PenPaola1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("PenPaola1")
    // 5 | click | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 6 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 7 | click | linkText=Logout |  | 
    await driver.findElement(By.linkText("Logout")).click()
    // 8 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 9 | close |  |  | 
    await driver.close()
  })
  it('Register', async function() {
    // Test name: Register
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    await driver.get("http://localhost:8080/")
    // 2 | setWindowSize | 1600x866 |  | 
    await driver.manage().window().setRect(1600, 866)
    // 3 | click | linkText=Registrati |  | 
    await driver.findElement(By.linkText("Registrati")).click()
    // 4 | click | css=li:nth-child(2) > label |  | 
    await driver.findElement(By.css("li:nth-child(2) > label")).click()
    // 5 | click | css=.forTutor > .form-label-group:nth-child(1) > label |  | 
    await driver.findElement(By.css(".forTutor > .form-label-group:nth-child(1) > label")).click()
    // 6 | type | id=inputNameT | Mario | 
    await driver.findElement(By.id("inputNameT")).sendKeys("Mario")
    // 7 | type | id=inputSurnameT | Rossi | 
    await driver.findElement(By.id("inputSurnameT")).sendKeys("Rossi")
    // 8 | type | id=inputEmailT | m.rossi@unisa.it | 
    await driver.findElement(By.id("inputEmailT")).sendKeys("m.rossi@unisa.it")
    // 9 | type | id=inputDepartmentT | Informatica | 
    await driver.findElement(By.id("inputDepartmentT")).sendKeys("Informatica")
    // 10 | type | id=inputPassword | ciaociao | 
    await driver.findElement(By.id("inputPassword")).sendKeys("ciaociao")
    // 11 | type | id=inputConfirmPassword | ciaociao | 
    await driver.findElement(By.id("inputConfirmPassword")).sendKeys("ciaociao")
    // 12 | click | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 13 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 14 | close |  |  | 
    await driver.close()
  })
  it('Search Chat', async function() {
    // Test name: Search Chat
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    await driver.get("http://localhost:8080/")
    // 2 | setWindowSize | 1600x866 |  | 
    await driver.manage().window().setRect(1600, 866)
    // 3 | type | id=inputUsername | p.penna@unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("p.penna@unisa.it")
    // 4 | type | id=inputPassword | PenPaola1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("PenPaola1")
    // 5 | click | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 6 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 7 | click | css=.fa-comment |  | 
    await driver.findElement(By.css(".fa-comment")).click()
    // 8 | click | id=input-search-chat |  | 
    await driver.findElement(By.id("input-search-chat")).click()
    // 9 | type | id=input-search-chat | alberto | 
    await driver.findElement(By.id("input-search-chat")).sendKeys("alberto")
    // 10 | sendKeys | id=input-search-chat | ${KEY_ENTER} | 
    await driver.findElement(By.id("input-search-chat")).sendKeys(Key.ENTER)
    // 11 | close |  |  | 
    await driver.close()
  })
  it('View Chat', async function() {
    // Test name: View Chat
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    await driver.get("http://localhost:8080/")
    // 2 | setWindowSize | 1600x866 |  | 
    await driver.manage().window().setRect(1600, 866)
    // 3 | type | id=inputUsername | p.penna@unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("p.penna@unisa.it")
    // 4 | type | id=inputPassword | PenPaola1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("PenPaola1")
    // 5 | sendKeys | id=inputPassword | ${KEY_ENTER} | 
    await driver.findElement(By.id("inputPassword")).sendKeys(Key.ENTER)
    // 6 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 7 | click | css=.fa-comment |  | 
    await driver.findElement(By.css(".fa-comment")).click()
    // 8 | click | css=.contact-container:nth-child(1) .user-info-email |  | 
    await driver.findElement(By.css(".contact-container:nth-child(1) .user-info-email")).click()
    // 9 | click | id=back-icon-chat |  | 
    await driver.findElement(By.id("back-icon-chat")).click()
    // 10 | click | id=minimize |  | 
    await driver.findElement(By.id("minimize")).click()
    // 11 | click | css=.infoBar |  | 
    await driver.findElement(By.css(".infoBar")).click()
    // 12 | click | id=close-chat |  | 
    await driver.findElement(By.id("close-chat")).click()
    // 13 | close |  |  | 
    await driver.close()
  })
})
