// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Default Suite', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('AcademicTutorListTest', async function() {
    // Test name: AcademicTutorListTest
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/ |  | 
    await driver.get("http://localhost:8080/")
    // 2 | type | id=inputUsername | f.califano@studenti.unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("f.califano@studenti.unisa.it")
    // 3 | type | id=inputPassword | FraCalifano1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("FraCalifano1")
    // 4 | click | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 5 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 6 | setWindowSize | 1280x722 |  | 
    await driver.manage().window().setRect(1280, 722)
    // 7 | runScript | window.scrollTo(0,0) |  | 
    await driver.executeScript("window.scrollTo(0,0)")
    // 8 | click | css=.nav-item:nth-child(4) p |  | 
    await driver.findElement(By.css(".nav-item:nth-child(4) p")).click()
    // 9 | runScript | window.scrollTo(0,0) |  | 
    await driver.executeScript("window.scrollTo(0,0)")
    // 10 | click | id=tipo |  | 
    await driver.findElement(By.id("tipo")).click()
    // 11 | select | id=tipo | label=Tutor Accademici | 
    {
      const dropdown = await driver.findElement(By.id("tipo"))
      await dropdown.findElement(By.xpath("//option[. = 'Tutor Accademici']")).click()
    }
    // 12 | click | id=academicTutor |  | 
    await driver.findElement(By.id("academicTutor")).click()
    // 13 | runScript | window.scrollTo(0,0) |  | 
    await driver.executeScript("window.scrollTo(0,0)")
  })
  it('ChatStudentTest', async function() {
    // Test name: ChatStudentTest
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/ |  | 
    await driver.get("http://localhost:8080/")
    // 2 | setWindowSize | 910x1153 |  | 
    await driver.manage().window().setRect(910, 1153)
    // 3 | click | css=.form-label-group:nth-child(1) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(1) > label")).click()
    // 4 | type | id=inputUsername | f.califano@studenti.unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("f.califano@studenti.unisa.it")
    // 5 | type | id=inputPassword | FraCalifano1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("FraCalifano1")
    // 6 | click | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 7 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 8 | click | css=.topbar-toggler |  | 
    await driver.findElement(By.css(".topbar-toggler")).click()
    // 9 | click | css=.fa-comment |  | 
    await driver.findElement(By.css(".fa-comment")).click()
    // 10 | click | css=.contact-container:nth-child(3) .user-info-email |  | 
    await driver.findElement(By.css(".contact-container:nth-child(3) .user-info-email")).click()
    // 11 | type | id=input-chat | Buonasera Paola! | 
    await driver.findElement(By.id("input-chat")).sendKeys("Buonasera Paola!")
    // 12 | click | css=body |  | 
    await driver.findElement(By.css("body")).click()
    // 13 | click | css=#form-chat > .sendButton |  | 
    await driver.findElement(By.css("#form-chat > .sendButton")).click()
    // 14 | mouseOver | css=#form-chat > .sendButton |  | 
    {
      const element = await driver.findElement(By.css("#form-chat > .sendButton"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 15 | mouseOut | css=#form-chat > .sendButton |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 16 | click | id=minimize |  | 
    await driver.findElement(By.id("minimize")).click()
    // 17 | click | linkText=Logout |  | 
    await driver.findElement(By.linkText("Logout")).click()
    // 18 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 19 | click | css=.form-label-group:nth-child(1) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(1) > label")).click()
    // 20 | type | id=inputUsername | p.penna@unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("p.penna@unisa.it")
    // 21 | click | css=.form-label-group:nth-child(2) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(2) > label")).click()
    // 22 | type | id=inputPassword | PenPaola1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("PenPaola1")
    // 23 | click | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 24 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 25 | click | css=.icon-options-vertical |  | 
    await driver.findElement(By.css(".icon-options-vertical")).click()
    // 26 | click | css=.fa-comment |  | 
    await driver.findElement(By.css(".fa-comment")).click()
    // 27 | click | id=studentButtonChat |  | 
    await driver.findElement(By.id("studentButtonChat")).click()
    // 28 | click | css=.contact-container:nth-child(1) .user-info-email |  | 
    await driver.findElement(By.css(".contact-container:nth-child(1) .user-info-email")).click()
    // 29 | click | id=input-chat |  | 
    await driver.findElement(By.id("input-chat")).click()
    // 30 | type | id=input-chat | Ciao Francexco | 
    await driver.findElement(By.id("input-chat")).sendKeys("Ciao Francexco")
    // 31 | click | css=#form-chat > .sendButton |  | 
    await driver.findElement(By.css("#form-chat > .sendButton")).click()
    // 32 | click | css=.chat-menu |  | 
    await driver.findElement(By.css(".chat-menu")).click()
    // 33 | mouseOver | css=.chat-menu |  | 
    {
      const element = await driver.findElement(By.css(".chat-menu"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 34 | mouseOut | css=.chat-menu |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 35 | click | css=.update-message > .button-menu |  | 
    await driver.findElement(By.css(".update-message > .button-menu")).click()
    // 36 | click | id=input-chat |  | 
    await driver.findElement(By.id("input-chat")).click()
    // 37 | type | id=input-chat | Ciao Francesco | 
    await driver.findElement(By.id("input-chat")).sendKeys("Ciao Francesco")
    // 38 | click | css=#form-chat > .sendButton |  | 
    await driver.findElement(By.css("#form-chat > .sendButton")).click()
    // 39 | click | css=#form-chat > .sendButton |  | 
    await driver.findElement(By.css("#form-chat > .sendButton")).click()
    // 40 | click | id=input-chat |  | 
    await driver.findElement(By.id("input-chat")).click()
    // 41 | type | id=input-chat | come va? | 
    await driver.findElement(By.id("input-chat")).sendKeys("come va?")
    // 42 | click | css=#form-chat > .sendButton |  | 
    await driver.findElement(By.css("#form-chat > .sendButton")).click()
    // 43 | click | css=.messageContainer:nth-child(3) .chat-menu |  | 
    await driver.findElement(By.css(".messageContainer:nth-child(3) .chat-menu")).click()
    // 44 | click | css=.popup-chat-menu |  | 
    await driver.findElement(By.css(".popup-chat-menu")).click()
    // 45 | click | css=.messageContainer:nth-child(3) .chat-menu |  | 
    await driver.findElement(By.css(".messageContainer:nth-child(3) .chat-menu")).click()
    // 46 | click | css=.remove-message > .button-menu |  | 
    await driver.findElement(By.css(".remove-message > .button-menu")).click()
    // 47 | click | css=.swal-button--confirm |  | 
    await driver.findElement(By.css(".swal-button--confirm")).click()
    // 48 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 49 | click | css=.leftInnerContainer |  | 
    await driver.findElement(By.css(".leftInnerContainer")).click()
  })
  it('DocumentCVStudentTest', async function() {
    // Test name: DocumentCVStudentTest
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/ |  | 
    await driver.get("http://localhost:8080/")
    // 2 | setWindowSize | 910x1153 |  | 
    await driver.manage().window().setRect(910, 1153)
    // 3 | type | id=inputUsername | f.califano@studenti.unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("f.califano@studenti.unisa.it")
    // 4 | type | id=inputPassword | FraCalifano1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("FraCalifano1")
    // 5 | sendKeys | id=inputPassword | ${KEY_ENTER} | 
    await driver.findElement(By.id("inputPassword")).sendKeys(Key.ENTER)
    // 6 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 7 | click | css=.navbar-toggler-icon > .icon-menu |  | 
    await driver.findElement(By.css(".navbar-toggler-icon > .icon-menu")).click()
    // 8 | click | css=.nav-item:nth-child(5) p |  | 
    await driver.findElement(By.css(".nav-item:nth-child(5) p")).click()
    // 9 | click | css=#doc > .input-label-upload |  | 
    await driver.findElement(By.css("#doc > .input-label-upload")).click()
    // 10 | click | css=.text-center > form > .btn |  | 
    await driver.findElement(By.css(".text-center > form > .btn")).click()
    // 11 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 12 | click | css=tr:nth-child(2) .download-image > img |  | 
    await driver.findElement(By.css("tr:nth-child(2) .download-image > img")).click()
  })
  it('DocumentIDStudentTest', async function() {
    // Test name: DocumentIDStudentTest
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/ |  | 
    await driver.get("http://localhost:8080/")
    // 2 | setWindowSize | 910x1153 |  | 
    await driver.manage().window().setRect(910, 1153)
    // 3 | type | id=inputUsername | f.califano@studenti.unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("f.califano@studenti.unisa.it")
    // 4 | type | id=inputPassword | FraCalifano1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("FraCalifano1")
    // 5 | sendKeys | id=inputPassword | ${KEY_ENTER} | 
    await driver.findElement(By.id("inputPassword")).sendKeys(Key.ENTER)
    // 6 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 7 | click | css=.navbar-toggler-icon > .icon-menu |  | 
    await driver.findElement(By.css(".navbar-toggler-icon > .icon-menu")).click()
    // 8 | click | css=.nav-item:nth-child(5) p |  | 
    await driver.findElement(By.css(".nav-item:nth-child(5) p")).click()
    // 9 | click | css=.text-center > form > .input-label-upload |  | 
    await driver.findElement(By.css(".text-center > form > .input-label-upload")).click()
    // 10 | click | css=#doc > .btn |  | 
    await driver.findElement(By.css("#doc > .btn")).click()
    // 11 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 12 | click | css=tr:nth-child(1) .download-image > img |  | 
    await driver.findElement(By.css("tr:nth-child(1) .download-image > img")).click()
  })
  it('ExternalTutorListTest', async function() {
    // Test name: ExternalTutorListTest
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/ |  | 
    await driver.get("http://localhost:8080/")
    // 2 | type | id=inputUsername | f.califano@studenti.unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("f.califano@studenti.unisa.it")
    // 3 | type | id=inputPassword | FraCalifano1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("FraCalifano1")
    // 4 | click | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 5 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 6 | setWindowSize | 1280x722 |  | 
    await driver.manage().window().setRect(1280, 722)
    // 7 | runScript | window.scrollTo(0,0) |  | 
    await driver.executeScript("window.scrollTo(0,0)")
    // 8 | click | css=.nav-item:nth-child(4) p |  | 
    await driver.findElement(By.css(".nav-item:nth-child(4) p")).click()
    // 9 | runScript | window.scrollTo(0,0) |  | 
    await driver.executeScript("window.scrollTo(0,0)")
    // 10 | click | id=tipo |  | 
    await driver.findElement(By.id("tipo")).click()
    // 11 | select | id=tipo | label=Tutor Esterni | 
    {
      const dropdown = await driver.findElement(By.id("tipo"))
      await dropdown.findElement(By.xpath("//option[. = 'Tutor Esterni']")).click()
    }
    // 12 | click | id=externalTutor |  | 
    await driver.findElement(By.id("externalTutor")).click()
    // 13 | runScript | window.scrollTo(0,0) |  | 
    await driver.executeScript("window.scrollTo(0,0)")
  })
  it('HostOrganizationListTest', async function() {
    // Test name: HostOrganizationListTest
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/ |  | 
    await driver.get("http://localhost:8080/")
    // 2 | type | id=inputUsername | f.califano@studenti.unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("f.califano@studenti.unisa.it")
    // 3 | type | id=inputPassword | FraCalifano1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("FraCalifano1")
    // 4 | click | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 5 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 6 | setWindowSize | 1280x722 |  | 
    await driver.manage().window().setRect(1280, 722)
    // 7 | runScript | window.scrollTo(0,0) |  | 
    await driver.executeScript("window.scrollTo(0,0)")
    // 8 | click | css=.nav-item:nth-child(4) p |  | 
    await driver.findElement(By.css(".nav-item:nth-child(4) p")).click()
    // 9 | runScript | window.scrollTo(0,0) |  | 
    await driver.executeScript("window.scrollTo(0,0)")
    // 10 | click | id=tipo |  | 
    await driver.findElement(By.id("tipo")).click()
    // 11 | select | id=tipo | label=Organizzazioni Ospitanti | 
    {
      const dropdown = await driver.findElement(By.id("tipo"))
      await dropdown.findElement(By.xpath("//option[. = 'Organizzazioni Ospitanti']")).click()
    }
    // 12 | click | id=hostOrganization |  | 
    await driver.findElement(By.id("hostOrganization")).click()
    // 13 | runScript | window.scrollTo(0,0) |  | 
    await driver.executeScript("window.scrollTo(0,0)")
  })
  it('LoginStudentTest', async function() {
    // Test name: LoginStudentTest
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/ |  | 
    await driver.get("http://localhost:8080/")
    // 2 | setWindowSize | 910x1153 |  | 
    await driver.manage().window().setRect(910, 1153)
    // 3 | type | id=inputUsername | f.califano@studenti.unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("f.califano@studenti.unisa.it")
    // 4 | type | id=inputPassword | FraCalifano1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("FraCalifano1")
    // 5 | click | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 6 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
  })
  it('LogoutStudentTest', async function() {
    // Test name: LogoutStudentTest
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/ |  | 
    await driver.get("http://localhost:8080/")
    // 2 | setWindowSize | 910x1153 |  | 
    await driver.manage().window().setRect(910, 1153)
    // 3 | click | css=.form-label-group:nth-child(1) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(1) > label")).click()
    // 4 | type | id=inputUsername | f.califano@studenti.unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("f.califano@studenti.unisa.it")
    // 5 | type | id=inputPassword | FraCalifano1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("FraCalifano1")
    // 6 | sendKeys | id=inputPassword | ${KEY_ENTER} | 
    await driver.findElement(By.id("inputPassword")).sendKeys(Key.ENTER)
    // 7 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 8 | click | css=.icon-options-vertical |  | 
    await driver.findElement(By.css(".icon-options-vertical")).click()
    // 9 | click | linkText=Logout |  | 
    await driver.findElement(By.linkText("Logout")).click()
    // 10 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
  })
  it('ProfileStudentTest', async function() {
    // Test name: ProfileStudentTest
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/ |  | 
    await driver.get("http://localhost:8080/")
    // 2 | type | id=inputUsername | f.califano@studenti.unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("f.califano@studenti.unisa.it")
    // 3 | type | id=inputPassword | FraCalifano1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("FraCalifano1")
    // 4 | sendKeys | id=inputPassword | ${KEY_ENTER} | 
    await driver.findElement(By.id("inputPassword")).sendKeys(Key.ENTER)
    // 5 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 6 | setWindowSize | 1280x540 |  | 
    await driver.manage().window().setRect(1280, 540)
    // 7 | runScript | window.scrollTo(0,0) |  | 
    await driver.executeScript("window.scrollTo(0,0)")
    // 8 | click | id=profile |  | 
    await driver.findElement(By.id("profile")).click()
    // 9 | runScript | window.scrollTo(0,0) |  | 
    await driver.executeScript("window.scrollTo(0,0)")
  })
  it('UpdateStudentProfileTest', async function() {
    // Test name: UpdateStudentProfileTest
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/ |  | 
    await driver.get("http://localhost:8080/")
    // 2 | setWindowSize | 1280x722 |  | 
    await driver.manage().window().setRect(1280, 722)
    // 3 | type | id=inputUsername | f.califano@studenti.unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("f.califano@studenti.unisa.it")
    // 4 | type | id=inputPassword | FraCalifano1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("FraCalifano1")
    // 5 | click | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 6 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 7 | click | id=profile |  | 
    await driver.findElement(By.id("profile")).click()
    // 8 | click | css=.btn-secondary:nth-child(2) |  | 
    await driver.findElement(By.css(".btn-secondary:nth-child(2)")).click()
    // 9 | click | id=inputNameS |  | 
    await driver.findElement(By.id("inputNameS")).click()
    // 10 | type | id=inputNameS | Francesco | 
    await driver.findElement(By.id("inputNameS")).sendKeys("Francesco")
    // 11 | type | id=inputSurnameS | Califano | 
    await driver.findElement(By.id("inputSurnameS")).sendKeys("Califano")
    // 12 | click | id=inputAddress |  | 
    await driver.findElement(By.id("inputAddress")).click()
    // 13 | type | id=inputAddress | Viale delle Tamerici 6 | 
    await driver.findElement(By.id("inputAddress")).sendKeys("Viale delle Tamerici 6")
    // 14 | click | id=inputCity |  | 
    await driver.findElement(By.id("inputCity")).click()
    // 15 | type | id=inputCity | Salerno | 
    await driver.findElement(By.id("inputCity")).sendKeys("Salerno")
    // 16 | click | id=inputDegree |  | 
    await driver.findElement(By.id("inputDegree")).click()
    // 17 | type | id=inputDegree | Informatica | 
    await driver.findElement(By.id("inputDegree")).sendKeys("Informatica")
    // 18 | click | id=inputOldPassword |  | 
    await driver.findElement(By.id("inputOldPassword")).click()
    // 19 | click | css=.btn:nth-child(7) |  | 
    await driver.findElement(By.css(".btn:nth-child(7)")).click()
    // 20 | runScript | window.scrollTo(0,0) |  | 
    await driver.executeScript("window.scrollTo(0,0)")
    // 21 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 22 | click | css=.btn-secondary:nth-child(2) |  | 
    await driver.findElement(By.css(".btn-secondary:nth-child(2)")).click()
    // 23 | click | id=inputOldPassword |  | 
    await driver.findElement(By.id("inputOldPassword")).click()
    // 24 | type | id=inputOldPassword | FraCalifano1 | 
    await driver.findElement(By.id("inputOldPassword")).sendKeys("FraCalifano1")
    // 25 | click | id=inputPassword |  | 
    await driver.findElement(By.id("inputPassword")).click()
    // 26 | type | id=inputPassword | FraCalifano11 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("FraCalifano11")
    // 27 | click | id=inputConfirmPassword |  | 
    await driver.findElement(By.id("inputConfirmPassword")).click()
    // 28 | type | id=inputConfirmPassword | FraCalifano11 | 
    await driver.findElement(By.id("inputConfirmPassword")).sendKeys("FraCalifano11")
    // 29 | click | css=.btn:nth-child(5) |  | 
    await driver.findElement(By.css(".btn:nth-child(5)")).click()
    // 30 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 31 | click | css=.btn-secondary:nth-child(2) |  | 
    await driver.findElement(By.css(".btn-secondary:nth-child(2)")).click()
    // 32 | click | id=inputOldPassword |  | 
    await driver.findElement(By.id("inputOldPassword")).click()
    // 33 | type | id=inputOldPassword | FraCalifano11 | 
    await driver.findElement(By.id("inputOldPassword")).sendKeys("FraCalifano11")
    // 34 | type | id=inputPassword | FraCalifano1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("FraCalifano1")
    // 35 | click | id=inputConfirmPassword |  | 
    await driver.findElement(By.id("inputConfirmPassword")).click()
    // 36 | type | id=inputConfirmPassword | FraCalifano1 | 
    await driver.findElement(By.id("inputConfirmPassword")).sendKeys("FraCalifano1")
    // 37 | click | css=.btn:nth-child(5) |  | 
    await driver.findElement(By.css(".btn:nth-child(5)")).click()
    // 38 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 39 | runScript | window.scrollTo(0,0) |  | 
    await driver.executeScript("window.scrollTo(0,0)")
  })
  it('ViewNotificationStudentTest', async function() {
    // Test name: ViewNotificationStudentTest
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/ |  | 
    await driver.get("http://localhost:8080/")
    // 2 | type | id=inputUsername | f.califano@studenti.unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("f.califano@studenti.unisa.it")
    // 3 | type | id=inputPassword | FraCalifano1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("FraCalifano1")
    // 4 | click | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 5 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 6 | setWindowSize | 1280x722 |  | 
    await driver.manage().window().setRect(1280, 722)
    // 7 | runScript | window.scrollTo(0,0) |  | 
    await driver.executeScript("window.scrollTo(0,0)")
    // 8 | click | css=.fa-bell |  | 
    await driver.findElement(By.css(".fa-bell")).click()
  })
  it('compileLAStudentTest', async function() {
    // Test name: compileLAStudentTest
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/ |  | 
    await driver.get("http://localhost:8080/")
    // 2 | type | id=inputUsername | f.califano@studenti.unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("f.califano@studenti.unisa.it")
    // 3 | type | id=inputPassword | FraCalifano1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("FraCalifano1")
    // 4 | click | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 5 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 6 | setWindowSize | 1280x722 |  | 
    await driver.manage().window().setRect(1280, 722)
    // 7 | runScript | window.scrollTo(0,0) |  | 
    await driver.executeScript("window.scrollTo(0,0)")
    // 8 | click | css=.nav-item:nth-child(2) p |  | 
    await driver.findElement(By.css(".nav-item:nth-child(2) p")).click()
    // 9 | runScript | window.scrollTo(0,0) |  | 
    await driver.executeScript("window.scrollTo(0,0)")
    // 10 | click | css=.form-label-group:nth-child(2) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(2) > label")).click()
    // 11 | type | id=inputName | Francesco | 
    await driver.findElement(By.id("inputName")).sendKeys("Francesco")
    // 12 | click | css=.form-label-group:nth-child(3) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(3) > label")).click()
    // 13 | type | id=inputSurname | Califano | 
    await driver.findElement(By.id("inputSurname")).sendKeys("Califano")
    // 14 | click | id=inputDate |  | 
    await driver.findElement(By.id("inputDate")).click()
    // 15 | type | id=inputDate | 1998-07-23 | 
    await driver.findElement(By.id("inputDate")).sendKeys("1998-07-23")
    // 16 | click | css=.form-label-group:nth-child(5) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(5) > label")).click()
    // 17 | type | id=inputTelephone | 3456171175 | 
    await driver.findElement(By.id("inputTelephone")).sendKeys("3456171175")
    // 18 | click | id=M |  | 
    await driver.findElement(By.id("M")).click()
    // 19 | click | css=.form-label-group:nth-child(7) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(7) > label")).click()
    // 20 | type | id=nationality | Italiana | 
    await driver.findElement(By.id("nationality")).sendKeys("Italiana")
    // 21 | click | id=1st |  | 
    await driver.findElement(By.id("1st")).click()
    // 22 | click | css=.form-label-group:nth-child(9) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(9) > label")).click()
    // 23 | type | id=inputAcademicYear1 | 19 | 
    await driver.findElement(By.id("inputAcademicYear1")).sendKeys("19")
    // 24 | click | css=.form-label-group:nth-child(10) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(10) > label")).click()
    // 25 | type | id=inputAcademicYear2 | 20 | 
    await driver.findElement(By.id("inputAcademicYear2")).sendKeys("20")
    // 26 | click | css=.form-label-group:nth-child(11) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(11) > label")).click()
    // 27 | type | id=inputSubjectCode | Informatica, 05121 | 
    await driver.findElement(By.id("inputSubjectCode")).sendKeys("Informatica, 05121")
    // 28 | click | css=.form-label-group:nth-child(12) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(12) > label")).click()
    // 29 | type | id=inputEmail | f.califano@studenti.unisa.it | 
    await driver.findElement(By.id("inputEmail")).sendKeys("f.califano@studenti.unisa.it")
    // 30 | click | css=.form-label-group:nth-child(16) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(16) > label")).click()
    // 31 | type | id=inputDepartmentSending | Informatica | 
    await driver.findElement(By.id("inputDepartmentSending")).sendKeys("Informatica")
    // 32 | click | css=.form-label-group:nth-child(17) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(17) > label")).click()
    // 33 | type | id=inputContactName | Filomena Ferrucci | 
    await driver.findElement(By.id("inputContactName")).sendKeys("Filomena Ferrucci")
    // 34 | click | css=.form-label-group:nth-child(18) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(18) > label")).click()
    // 35 | type | id=inputContactSending | f.ferrucci@unisa.it 123456789 | 
    await driver.findElement(By.id("inputContactSending")).sendKeys("f.ferrucci@unisa.it 123456789")
    // 36 | click | css=.form-label-group:nth-child(22) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(22) > label")).click()
    // 37 | type | id=inputNameSector | Google | 
    await driver.findElement(By.id("inputNameSector")).sendKeys("Google")
    // 38 | click | css=.form-label-group:nth-child(23) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(23) > label")).click()
    // 39 | type | id=inputDepartmentReciving | Informatica | 
    await driver.findElement(By.id("inputDepartmentReciving")).sendKeys("Informatica")
    // 40 | click | css=.form-label-group:nth-child(24) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(24) > label")).click()
    // 41 | type | id=inputAddress | Via delle foglie 15 | 
    await driver.findElement(By.id("inputAddress")).sendKeys("Via delle foglie 15")
    // 42 | click | css=.form-label-group:nth-child(25) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(25) > label")).click()
    // 43 | type | id=inputWebSite | www.ciao.com | 
    await driver.findElement(By.id("inputWebSite")).sendKeys("www.ciao.com")
    // 44 | click | id=inlineFormCustomSelect |  | 
    await driver.findElement(By.id("inlineFormCustomSelect")).click()
    // 45 | select | id=inlineFormCustomSelect | label=Italia | 
    {
      const dropdown = await driver.findElement(By.id("inlineFormCustomSelect"))
      await dropdown.findElement(By.xpath("//option[. = 'Italia']")).click()
    }
    // 46 | click | css=option:nth-child(108) |  | 
    await driver.findElement(By.css("option:nth-child(108)")).click()
    // 47 | click | css=.form-label-group:nth-child(27) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(27) > label")).click()
    // 48 | type | id=inputSizeEnterprise | 450 | 
    await driver.findElement(By.id("inputSizeEnterprise")).sendKeys("450")
    // 49 | click | css=.form-label-group:nth-child(28) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(28) > label")).click()
    // 50 | type | id=inputContactRecivingName | Sara Cotto | 
    await driver.findElement(By.id("inputContactRecivingName")).sendKeys("Sara Cotto")
    // 51 | click | css=.form-label-group:nth-child(29) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(29) > label")).click()
    // 52 | click | id=inputContactRecivingName |  | 
    await driver.findElement(By.id("inputContactRecivingName")).click()
    // 53 | type | id=inputContactRecivingName | Alessandro Galezzi | 
    await driver.findElement(By.id("inputContactRecivingName")).sendKeys("Alessandro Galezzi")
    // 54 | click | css=.form-label-group:nth-child(29) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(29) > label")).click()
    // 55 | type | id=inputContactRecivingPosition | Dirigente | 
    await driver.findElement(By.id("inputContactRecivingPosition")).sendKeys("Dirigente")
    // 56 | click | css=.form-label-group:nth-child(30) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(30) > label")).click()
    // 57 | type | id=inputMentorName | Sara Cotto | 
    await driver.findElement(By.id("inputMentorName")).sendKeys("Sara Cotto")
    // 58 | click | css=.form-label-group:nth-child(31) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(31) > label")).click()
    // 59 | type | id=inputMentorPosition | Tutor Esterno | 
    await driver.findElement(By.id("inputMentorPosition")).sendKeys("Tutor Esterno")
    // 60 | click | css=.form-label-group:nth-child(32) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(32) > label")).click()
    // 61 | type | id=inputMentorInfo | s.cotto@gmail.com 123456789 | 
    await driver.findElement(By.id("inputMentorInfo")).sendKeys("s.cotto@gmail.com 123456789")
    // 62 | click | css=.form-label-group:nth-child(37) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(37) > label")).click()
    // 63 | type | id=inputDateFrom | 01/2020 | 
    await driver.findElement(By.id("inputDateFrom")).sendKeys("01/2020")
    // 64 | click | css=.form-label-group:nth-child(39) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(39) > label")).click()
    // 65 | click | id=inputHourWork |  | 
    await driver.findElement(By.id("inputHourWork")).click()
    // 66 | type | id=inputHourWork | 7 | 
    await driver.findElement(By.id("inputHourWork")).sendKeys("7")
    // 67 | type | id=inputDateTo | 07/2020 | 
    await driver.findElement(By.id("inputDateTo")).sendKeys("07/2020")
    // 68 | click | css=.form-label-group:nth-child(44) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(44) > label")).click()
    // 69 | type | id=inputTitle | Traineeship | 
    await driver.findElement(By.id("inputTitle")).sendKeys("Traineeship")
    // 70 | click | id=inputDetailed |  | 
    await driver.findElement(By.id("inputDetailed")).click()
    // 71 | type | id=inputDetailed | Apprendimento di nuovi tool. | 
    await driver.findElement(By.id("inputDetailed")).sendKeys("Apprendimento di nuovi tool.")
    // 72 | click | id=inputKnowledge |  | 
    await driver.findElement(By.id("inputKnowledge")).click()
    // 73 | type | id=inputKnowledge | Conoscenze acquisite riguardanti NodeJS, MongoDB, MochaandChai, Selenium e GitHub. | 
    await driver.findElement(By.id("inputKnowledge")).sendKeys("Conoscenze acquisite riguardanti NodeJS, MongoDB, MochaandChai, Selenium e GitHub.")
    // 74 | click | id=inputMonitoring |  | 
    await driver.findElement(By.id("inputMonitoring")).click()
    // 75 | type | id=inputMonitoring | Basato su ore lavorative settimanali. | 
    await driver.findElement(By.id("inputMonitoring")).sendKeys("Basato su ore lavorative settimanali.")
    // 76 | click | css=.form-label-group:nth-child(56) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(56) > label")).click()
    // 77 | type | id=inputEvaluation | Basato su crediti formativi. | 
    await driver.findElement(By.id("inputEvaluation")).sendKeys("Basato su crediti formativi.")
    // 78 | click | id=formCompile |  | 
    await driver.findElement(By.id("formCompile")).click()
    // 79 | click | id=inputLenguage |  | 
    await driver.findElement(By.id("inputLenguage")).click()
    // 80 | select | id=inputLenguage | label=Inglese | 
    {
      const dropdown = await driver.findElement(By.id("inputLenguage"))
      await dropdown.findElement(By.xpath("//option[. = 'Inglese']")).click()
    }
    // 81 | click | css=#inputLenguage > option:nth-child(16) |  | 
    await driver.findElement(By.css("#inputLenguage > option:nth-child(16)")).click()
    // 82 | click | id=B1 |  | 
    await driver.findElement(By.id("B1")).click()
    // 83 | click | id=send |  | 
    await driver.findElement(By.id("send")).click()
  })
  it('registerStudentTest', async function() {
    // Test name: registerStudentTest
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/ |  | 
    await driver.get("http://localhost:8080/")
    // 2 | setWindowSize | 919x1133 |  | 
    await driver.manage().window().setRect(919, 1133)
    // 3 | click | linkText=Registrati |  | 
    await driver.findElement(By.linkText("Registrati")).click()
    // 4 | click | css=.forStudent > .form-label-group:nth-child(1) > label |  | 
    await driver.findElement(By.css(".forStudent > .form-label-group:nth-child(1) > label")).click()
    // 5 | type | id=inputName | Angela | 
    await driver.findElement(By.id("inputName")).sendKeys("Angela")
    // 6 | type | id=inputSurname | DeMartino | 
    await driver.findElement(By.id("inputSurname")).sendKeys("DeMartino")
    // 7 | type | id=inputEmail | a.demartino6@studenti.unisa.it | 
    await driver.findElement(By.id("inputEmail")).sendKeys("a.demartino6@studenti.unisa.it")
    // 8 | type | id=inputMatricola | 0517105561 | 
    await driver.findElement(By.id("inputMatricola")).sendKeys("0517105561")
    // 9 | click | css=.forStudent > .form-label-group:nth-child(5) > label |  | 
    await driver.findElement(By.css(".forStudent > .form-label-group:nth-child(5) > label")).click()
    // 10 | type | id=inputCity | Salerno | 
    await driver.findElement(By.id("inputCity")).sendKeys("Salerno")
    // 11 | click | css=.forStudent > .form-label-group:nth-child(6) > label |  | 
    await driver.findElement(By.css(".forStudent > .form-label-group:nth-child(6) > label")).click()
    // 12 | type | id=inputAddress | via della Memoria, 33 | 
    await driver.findElement(By.id("inputAddress")).sendKeys("via della Memoria, 33")
    // 13 | click | css=.form-label-group:nth-child(7) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(7) > label")).click()
    // 14 | type | id=inputCourse | Informatica | 
    await driver.findElement(By.id("inputCourse")).sendKeys("Informatica")
    // 15 | click | css=#formSignUp > .form-label-group:nth-child(5) > label |  | 
    await driver.findElement(By.css("#formSignUp > .form-label-group:nth-child(5) > label")).click()
    // 16 | type | id=inputPassword | Ciaomamma99 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("Ciaomamma99")
    // 17 | type | id=inputConfirmPassword | Ciaomamma99 | 
    await driver.findElement(By.id("inputConfirmPassword")).sendKeys("Ciaomamma99")
    // 18 | click | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 19 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
  })
  it('viewLAstudent', async function() {
    // Test name: viewLAstudent
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/ |  | 
    await driver.get("http://localhost:8080/")
    // 2 | type | id=inputUsername | f.califano@studenti.unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("f.califano@studenti.unisa.it")
    // 3 | type | id=inputPassword | FraCalifano1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("FraCalifano1")
    // 4 | sendKeys | id=inputPassword | ${KEY_ENTER} | 
    await driver.findElement(By.id("inputPassword")).sendKeys(Key.ENTER)
    // 5 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 6 | setWindowSize | 1280x540 |  | 
    await driver.manage().window().setRect(1280, 540)
    // 7 | runScript | window.scrollTo(0,0) |  | 
    await driver.executeScript("window.scrollTo(0,0)")
    // 8 | click | css=.nav-item:nth-child(3) p |  | 
    await driver.findElement(By.css(".nav-item:nth-child(3) p")).click()
    // 9 | runScript | window.scrollTo(0,0) |  | 
    await driver.executeScript("window.scrollTo(0,0)")
    // 10 | click | css=.btn-secondary |  | 
    await driver.findElement(By.css(".btn-secondary")).click()
  })
})
