// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Default Suite', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('AcademicTutorListTest', async function() {
    // Test name: AcademicTutorListTest
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/ |  | 
    await driver.get("http://localhost:8080/")
    // 2 | type | id=inputUsername | s.cotto@gmail.com | 
    await driver.findElement(By.id("inputUsername")).sendKeys("s.cotto@gmail.com")
    // 3 | type | id=inputPassword | sara1234 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("sara1234")
    // 4 | click | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 5 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 6 | setWindowSize | 1280x571 |  | 
    await driver.manage().window().setRect(1280, 571)
    // 7 | runScript | window.scrollTo(0,0) |  | 
    await driver.executeScript("window.scrollTo(0,0)")
    // 8 | click | css=.nav-item:nth-child(3) p |  | 
    await driver.findElement(By.css(".nav-item:nth-child(3) p")).click()
    // 9 | click | id=tipo |  | 
    await driver.findElement(By.id("tipo")).click()
    // 10 | select | id=tipo | label=Tutor Accademici | 
    {
      const dropdown = await driver.findElement(By.id("tipo"))
      await dropdown.findElement(By.xpath("//option[. = 'Tutor Accademici']")).click()
    }
    // 11 | click | id=externalTutor |  | 
    await driver.findElement(By.id("externalTutor")).click()
    // 12 | runScript | window.scrollTo(0,0) |  | 
    await driver.executeScript("window.scrollTo(0,0)")
  })
  it('ChatExternalTutorTest', async function() {
    // Test name: ChatExternalTutorTest
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/ |  | 
    await driver.get("http://localhost:8080/")
    // 2 | setWindowSize | 1600x866 |  | 
    await driver.manage().window().setRect(1600, 866)
    // 3 | type | id=inputUsername | s.cotto@gmail.com | 
    await driver.findElement(By.id("inputUsername")).sendKeys("s.cotto@gmail.com")
    // 4 | type | id=inputPassword | sara1234 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("sara1234")
    // 5 | sendKeys | id=inputPassword | ${KEY_ENTER} | 
    await driver.findElement(By.id("inputPassword")).sendKeys(Key.ENTER)
    // 6 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 7 | click | id=open-chat |  | 
    await driver.findElement(By.id("open-chat")).click()
    // 8 | click | css=.contact-container:nth-child(1) .user-info-email |  | 
    await driver.findElement(By.css(".contact-container:nth-child(1) .user-info-email")).click()
    // 9 | click | id=input-chat |  | 
    await driver.findElement(By.id("input-chat")).click()
    // 10 | type | id=input-chat | ciao | 
    await driver.findElement(By.id("input-chat")).sendKeys("ciao")
    // 11 | click | css=#form-chat > .sendButton |  | 
    await driver.findElement(By.css("#form-chat > .sendButton")).click()
    // 12 | click | css=.chat-menu |  | 
    await driver.findElement(By.css(".chat-menu")).click()
    // 13 | click | css=.update-message > .button-menu |  | 
    await driver.findElement(By.css(".update-message > .button-menu")).click()
    // 14 | doubleClick | id=input-chat |  | 
    {
      const element = await driver.findElement(By.id("input-chat"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 15 | type | id=input-chat | wewe | 
    await driver.findElement(By.id("input-chat")).sendKeys("wewe")
    // 16 | click | css=#form-chat > .sendButton |  | 
    await driver.findElement(By.css("#form-chat > .sendButton")).click()
    // 17 | click | css=.chat-menu |  | 
    await driver.findElement(By.css(".chat-menu")).click()
    // 18 | click | css=.remove-message > .button-menu |  | 
    await driver.findElement(By.css(".remove-message > .button-menu")).click()
    // 19 | click | css=.swal-button--confirm |  | 
    await driver.findElement(By.css(".swal-button--confirm")).click()
    // 20 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 21 | click | id=minimize |  | 
    await driver.findElement(By.id("minimize")).click()
    // 22 | click | css=.infoBar |  | 
    await driver.findElement(By.css(".infoBar")).click()
    // 23 | click | id=back-icon-chat |  | 
    await driver.findElement(By.id("back-icon-chat")).click()
    // 24 | click | id=studentButtonChat |  | 
    await driver.findElement(By.id("studentButtonChat")).click()
    // 25 | click | id=close-chat |  | 
    await driver.findElement(By.id("close-chat")).click()
    // 26 | close |  |  | 
    await driver.close()
  })
  it('DisapproveLAExternalTutorTest', async function() {
    // Test name: DisapproveLAExternalTutorTest
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/ |  | 
    await driver.get("http://localhost:8080/")
    // 2 | setWindowSize | 910x1153 |  | 
    await driver.manage().window().setRect(910, 1153)
    // 3 | click | css=.form-label-group:nth-child(1) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(1) > label")).click()
    // 4 | type | id=inputUsername | g.mosconi@studenti.unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("g.mosconi@studenti.unisa.it")
    // 5 | type | id=inputPassword | MoscGermano1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("MoscGermano1")
    // 6 | sendKeys | id=inputPassword | ${KEY_ENTER} | 
    await driver.findElement(By.id("inputPassword")).sendKeys(Key.ENTER)
    // 7 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 8 | click | css=.navbar-toggler-icon > .icon-menu |  | 
    await driver.findElement(By.css(".navbar-toggler-icon > .icon-menu")).click()
    // 9 | click | css=.nav-item:nth-child(2) p |  | 
    await driver.findElement(By.css(".nav-item:nth-child(2) p")).click()
    // 10 | click | css=.form-label-group:nth-child(2) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(2) > label")).click()
    // 11 | type | id=inputName | Germano | 
    await driver.findElement(By.id("inputName")).sendKeys("Germano")
    // 12 | type | id=inputSurname | Mosconi | 
    await driver.findElement(By.id("inputSurname")).sendKeys("Mosconi")
    // 13 | type | id=inputDate | 1998-01-11 | 
    await driver.findElement(By.id("inputDate")).sendKeys("1998-01-11")
    // 14 | click | css=.form-label-group:nth-child(5) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(5) > label")).click()
    // 15 | type | id=inputTelephone | 3334445558 | 
    await driver.findElement(By.id("inputTelephone")).sendKeys("3334445558")
    // 16 | click | id=M |  | 
    await driver.findElement(By.id("M")).click()
    // 17 | click | css=.form-label-group:nth-child(7) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(7) > label")).click()
    // 18 | type | id=nationality | Italia | 
    await driver.findElement(By.id("nationality")).sendKeys("Italia")
    // 19 | click | id=1st |  | 
    await driver.findElement(By.id("1st")).click()
    // 20 | click | css=.form-label-group:nth-child(9) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(9) > label")).click()
    // 21 | type | id=inputAcademicYear1 | 19 | 
    await driver.findElement(By.id("inputAcademicYear1")).sendKeys("19")
    // 22 | type | id=inputAcademicYear2 | 20 | 
    await driver.findElement(By.id("inputAcademicYear2")).sendKeys("20")
    // 23 | type | id=inputSubjectCode | I | 
    await driver.findElement(By.id("inputSubjectCode")).sendKeys("I")
    // 24 | click | id=inputSubjectCode |  | 
    await driver.findElement(By.id("inputSubjectCode")).click()
    // 25 | type | id=inputSubjectCode | Informatica, 05121 | 
    await driver.findElement(By.id("inputSubjectCode")).sendKeys("Informatica, 05121")
    // 26 | type | id=inputEmail | g.mosconi@studenti.unisa.it | 
    await driver.findElement(By.id("inputEmail")).sendKeys("g.mosconi@studenti.unisa.it")
    // 27 | click | css=.form-label-group:nth-child(16) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(16) > label")).click()
    // 28 | type | id=inputDepartmentSending | Informatica | 
    await driver.findElement(By.id("inputDepartmentSending")).sendKeys("Informatica")
    // 29 | click | css=.form-label-group:nth-child(17) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(17) > label")).click()
    // 30 | type | id=inputContactName | Lorenzo Nebiolo | 
    await driver.findElement(By.id("inputContactName")).sendKeys("Lorenzo Nebiolo")
    // 31 | type | id=inputContactSending | l.nebiolo@unisa.it 3334445512 | 
    await driver.findElement(By.id("inputContactSending")).sendKeys("l.nebiolo@unisa.it 3334445512")
    // 32 | type | id=inputNameSector | Apple | 
    await driver.findElement(By.id("inputNameSector")).sendKeys("Apple")
    // 33 | type | id=inputDepartmentReciving | Informatica | 
    await driver.findElement(By.id("inputDepartmentReciving")).sendKeys("Informatica")
    // 34 | type | id=inputAddress | Via Kennedy | 
    await driver.findElement(By.id("inputAddress")).sendKeys("Via Kennedy")
    // 35 | type | id=inputWebSite | www.apple.it | 
    await driver.findElement(By.id("inputWebSite")).sendKeys("www.apple.it")
    // 36 | select | id=inlineFormCustomSelect | label=Kirghizistan | 
    {
      const dropdown = await driver.findElement(By.id("inlineFormCustomSelect"))
      await dropdown.findElement(By.xpath("//option[. = 'Kirghizistan']")).click()
    }
    // 37 | click | id=inlineFormCustomSelect |  | 
    await driver.findElement(By.id("inlineFormCustomSelect")).click()
    // 38 | select | id=inlineFormCustomSelect | label=Italia | 
    {
      const dropdown = await driver.findElement(By.id("inlineFormCustomSelect"))
      await dropdown.findElement(By.xpath("//option[. = 'Italia']")).click()
    }
    // 39 | click | id=inlineFormCustomSelect |  | 
    await driver.findElement(By.id("inlineFormCustomSelect")).click()
    // 40 | click | css=.form-label-group:nth-child(27) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(27) > label")).click()
    // 41 | type | id=inputSizeEnterprise | 1-50 | 
    await driver.findElement(By.id("inputSizeEnterprise")).sendKeys("1-50")
    // 42 | type | id=inputContactRecivingName | Filomena Ferrucci | 
    await driver.findElement(By.id("inputContactRecivingName")).sendKeys("Filomena Ferrucci")
    // 43 | type | id=inputContactRecivingPosition | Salerno | 
    await driver.findElement(By.id("inputContactRecivingPosition")).sendKeys("Salerno")
    // 44 | type | id=inputMentorName | Sara Cotto | 
    await driver.findElement(By.id("inputMentorName")).sendKeys("Sara Cotto")
    // 45 | type | id=inputMentorPosition | Fisciano | 
    await driver.findElement(By.id("inputMentorPosition")).sendKeys("Fisciano")
    // 46 | type | id=inputMentorInfo | s.cotto@gmail.com 3334445566 | 
    await driver.findElement(By.id("inputMentorInfo")).sendKeys("s.cotto@gmail.com 3334445566")
    // 47 | click | css=.form-label-group:nth-child(37) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(37) > label")).click()
    // 48 | type | id=inputDateFrom | 02/2020 | 
    await driver.findElement(By.id("inputDateFrom")).sendKeys("02/2020")
    // 49 | type | id=inputDateTo | 09/2021 | 
    await driver.findElement(By.id("inputDateTo")).sendKeys("09/2021")
    // 50 | type | id=inputDateTo | 09/2020 | 
    await driver.findElement(By.id("inputDateTo")).sendKeys("09/2020")
    // 51 | click | id=inputHourWork |  | 
    await driver.findElement(By.id("inputHourWork")).click()
    // 52 | type | id=inputHourWork | 4 | 
    await driver.findElement(By.id("inputHourWork")).sendKeys("4")
    // 53 | click | id=formCompile |  | 
    await driver.findElement(By.id("formCompile")).click()
    // 54 | click | css=.form-label-group:nth-child(44) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(44) > label")).click()
    // 55 | type | id=inputTitle | Erasmus | 
    await driver.findElement(By.id("inputTitle")).sendKeys("Erasmus")
    // 56 | type | id=inputDetailed | Piattaforma web per la gestione dell'erasmus | 
    await driver.findElement(By.id("inputDetailed")).sendKeys("Piattaforma web per la gestione dell\'erasmus")
    // 57 | click | id=inputKnowledge |  | 
    await driver.findElement(By.id("inputKnowledge")).click()
    // 58 | type | id=inputKnowledge | javascript, dbnosql, pyhton | 
    await driver.findElement(By.id("inputKnowledge")).sendKeys("javascript, dbnosql, pyhton")
    // 59 | click | id=inputMonitoring |  | 
    await driver.findElement(By.id("inputMonitoring")).click()
    // 60 | type | id=inputMonitoring | report settimanale | 
    await driver.findElement(By.id("inputMonitoring")).sendKeys("report settimanale")
    // 61 | type | id=inputEvaluation | valutazione fine progetto | 
    await driver.findElement(By.id("inputEvaluation")).sendKeys("valutazione fine progetto")
    // 62 | select | id=inputLenguage | label=Inglese | 
    {
      const dropdown = await driver.findElement(By.id("inputLenguage"))
      await dropdown.findElement(By.xpath("//option[. = 'Inglese']")).click()
    }
    // 63 | click | id=inputLenguage |  | 
    await driver.findElement(By.id("inputLenguage")).click()
    // 64 | click | id=B2 |  | 
    await driver.findElement(By.id("B2")).click()
    // 65 | click | id=send |  | 
    await driver.findElement(By.id("send")).click()
    // 66 | open | http://localhost:8080/logout |  | 
    await driver.get("http://localhost:8080/logout")
    // 67 | click | css=.form-label-group:nth-child(1) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(1) > label")).click()
    // 68 | type | id=inputUsername | l.nebiolo@unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("l.nebiolo@unisa.it")
    // 69 | click | css=.form-label-group:nth-child(2) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(2) > label")).click()
    // 70 | click | css=.form-label-group:nth-child(2) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(2) > label")).click()
    // 71 | type | id=inputPassword | NebLorenzo1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("NebLorenzo1")
    // 72 | click | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 73 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 74 | click | css=.navbar-toggler-icon > .icon-menu |  | 
    await driver.findElement(By.css(".navbar-toggler-icon > .icon-menu")).click()
    // 75 | click | css=.nav-item:nth-child(2) p |  | 
    await driver.findElement(By.css(".nav-item:nth-child(2) p")).click()
    // 76 | click | linkText=Visualizza |  | 
    await driver.findElement(By.linkText("Visualizza")).click()
    // 77 | click | id=approve1 |  | 
    await driver.findElement(By.id("approve1")).click()
    // 78 | click | id=inputCredits |  | 
    await driver.findElement(By.id("inputCredits")).click()
    // 79 | type | id=inputCredits | 6 | 
    await driver.findElement(By.id("inputCredits")).sendKeys("6")
    // 80 | click | id=inputCertificate |  | 
    await driver.findElement(By.id("inputCertificate")).click()
    // 81 | click | id=inputRadio1 |  | 
    await driver.findElement(By.id("inputRadio1")).click()
    // 82 | click | id=send |  | 
    await driver.findElement(By.id("send")).click()
    // 83 | open | http://localhost:8080/logout |  | 
    await driver.get("http://localhost:8080/logout")
    // 84 | type | id=inputUsername | s.cotto@gmail.com | 
    await driver.findElement(By.id("inputUsername")).sendKeys("s.cotto@gmail.com")
    // 85 | type | id=inputPassword | sara1234 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("sara1234")
    // 86 | sendKeys | id=inputPassword | ${KEY_ENTER} | 
    await driver.findElement(By.id("inputPassword")).sendKeys(Key.ENTER)
    // 87 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 88 | click | css=.navbar-toggler |  | 
    await driver.findElement(By.css(".navbar-toggler")).click()
    // 89 | click | linkText=Visualizza Richieste |  | 
    await driver.findElement(By.linkText("Visualizza Richieste")).click()
    // 90 | click | linkText=Visualizza |  | 
    await driver.findElement(By.linkText("Visualizza")).click()
    // 91 | click | id=disapprove |  | 
    await driver.findElement(By.id("disapprove")).click()
    // 92 | click | name=msg |  | 
    await driver.findElement(By.name("msg")).click()
    // 93 | type | name=msg | Certificato lingua inglese non idonea. | 
    await driver.findElement(By.name("msg")).sendKeys("Certificato lingua inglese non idonea.")
    // 94 | click | css=.btn-block:nth-child(2) |  | 
    await driver.findElement(By.css(".btn-block:nth-child(2)")).click()
  })
  it('EditPasswordExternalTutorTest', async function() {
    // Test name: EditPasswordExternalTutorTest
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/ |  | 
    await driver.get("http://localhost:8080/")
    // 2 | type | id=inputUsername | s.cotto@gmail.com | 
    await driver.findElement(By.id("inputUsername")).sendKeys("s.cotto@gmail.com")
    // 3 | click | css=.form-label-group:nth-child(2) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(2) > label")).click()
    // 4 | type | id=inputPassword | sara1234 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("sara1234")
    // 5 | click | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 6 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 7 | setWindowSize | 1280x721 |  | 
    await driver.manage().window().setRect(1280, 721)
    // 8 | click | id=profile |  | 
    await driver.findElement(By.id("profile")).click()
    // 9 | click | css=.btn-secondary:nth-child(2) |  | 
    await driver.findElement(By.css(".btn-secondary:nth-child(2)")).click()
    // 10 | click | id=inputOldPassword |  | 
    await driver.findElement(By.id("inputOldPassword")).click()
    // 11 | type | id=inputOldPassword | sara1234 | 
    await driver.findElement(By.id("inputOldPassword")).sendKeys("sara1234")
    // 12 | click | id=inputPassword |  | 
    await driver.findElement(By.id("inputPassword")).click()
    // 13 | type | id=inputPassword | sara1990 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("sara1990")
    // 14 | click | id=inputConfirmPassword |  | 
    await driver.findElement(By.id("inputConfirmPassword")).click()
    // 15 | type | id=inputConfirmPassword | sara1990 | 
    await driver.findElement(By.id("inputConfirmPassword")).sendKeys("sara1990")
    // 16 | click | css=#formUpdatePass > .btn |  | 
    await driver.findElement(By.css("#formUpdatePass > .btn")).click()
    // 17 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 18 | open | http://localhost:8080/logout |  | 
    await driver.get("http://localhost:8080/logout")
    // 19 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 20 | type | id=inputUsername | s.cotto@gmail.com | 
    await driver.findElement(By.id("inputUsername")).sendKeys("s.cotto@gmail.com")
    // 21 | type | id=inputPassword | sara1990 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("sara1990")
    // 22 | click | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 23 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 24 | click | id=profile |  | 
    await driver.findElement(By.id("profile")).click()
    // 25 | click | css=.btn-secondary:nth-child(2) |  | 
    await driver.findElement(By.css(".btn-secondary:nth-child(2)")).click()
    // 26 | click | id=inputOldPassword |  | 
    await driver.findElement(By.id("inputOldPassword")).click()
    // 27 | type | id=inputOldPassword | sara1990 | 
    await driver.findElement(By.id("inputOldPassword")).sendKeys("sara1990")
    // 28 | type | id=inputPassword | sara1234 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("sara1234")
    // 29 | type | id=inputConfirmPassword | sara1234 | 
    await driver.findElement(By.id("inputConfirmPassword")).sendKeys("sara1234")
    // 30 | click | css=#formUpdatePass > .btn |  | 
    await driver.findElement(By.css("#formUpdatePass > .btn")).click()
    // 31 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
  })
  it('EditPersonalDataExternalTutorTest', async function() {
    // Test name: EditPersonalDataExternalTutorTest
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/ |  | 
    await driver.get("http://localhost:8080/")
    // 2 | setWindowSize | 1600x866 |  | 
    await driver.manage().window().setRect(1600, 866)
    // 3 | type | id=inputUsername | s.cotto@gmail.com | 
    await driver.findElement(By.id("inputUsername")).sendKeys("s.cotto@gmail.com")
    // 4 | type | id=inputPassword | sara1234 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("sara1234")
    // 5 | click | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 6 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 7 | click | id=profile |  | 
    await driver.findElement(By.id("profile")).click()
    // 8 | click | css=.btn-secondary:nth-child(2) |  | 
    await driver.findElement(By.css(".btn-secondary:nth-child(2)")).click()
    // 9 | click | id=inputNameE |  | 
    await driver.findElement(By.id("inputNameE")).click()
    // 10 | type | id=inputNameE | Sara | 
    await driver.findElement(By.id("inputNameE")).sendKeys("Sara")
    // 11 | click | id=inputSurnameE |  | 
    await driver.findElement(By.id("inputSurnameE")).click()
    // 12 | type | id=inputSurnameE | Cotto | 
    await driver.findElement(By.id("inputSurnameE")).sendKeys("Cotto")
    // 13 | click | id=inputOrganization |  | 
    await driver.findElement(By.id("inputOrganization")).click()
    // 14 | type | id=inputOrganization | Google | 
    await driver.findElement(By.id("inputOrganization")).sendKeys("Google")
    // 15 | click | css=#formUpdate > .btn |  | 
    await driver.findElement(By.css("#formUpdate > .btn")).click()
    // 16 | runScript | window.scrollTo(0,0) |  | 
    await driver.executeScript("window.scrollTo(0,0)")
    // 17 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
  })
  it('ExternalTutorLoginTest', async function() {
    // Test name: ExternalTutorLoginTest
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/ |  | 
    await driver.get("http://localhost:8080/")
    // 2 | setWindowSize | 1280x570 |  | 
    await driver.manage().window().setRect(1280, 570)
    // 3 | type | id=inputUsername | s.cotto@gmail.com | 
    await driver.findElement(By.id("inputUsername")).sendKeys("s.cotto@gmail.com")
    // 4 | click | css=.form-label-group:nth-child(2) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(2) > label")).click()
    // 5 | type | id=inputPassword | sara1234 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("sara1234")
    // 6 | click | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 7 | runScript | window.scrollTo(0,0) |  | 
    await driver.executeScript("window.scrollTo(0,0)")
  })
  it('ExternalTutorLogoutTest', async function() {
    // Test name: ExternalTutorLogoutTest
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/ |  | 
    await driver.get("http://localhost:8080/")
    // 2 | type | id=inputUsername | s.cotto@gmail.com | 
    await driver.findElement(By.id("inputUsername")).sendKeys("s.cotto@gmail.com")
    // 3 | type | id=inputPassword | sara1234 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("sara1234")
    // 4 | sendKeys | id=inputPassword | ${KEY_ENTER} | 
    await driver.findElement(By.id("inputPassword")).sendKeys(Key.ENTER)
    // 5 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 6 | setWindowSize | 1280x721 |  | 
    await driver.manage().window().setRect(1280, 721)
    // 7 | runScript | window.scrollTo(0,0) |  | 
    await driver.executeScript("window.scrollTo(0,0)")
    // 8 | click | linkText=Logout |  | 
    await driver.findElement(By.linkText("Logout")).click()
    // 9 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
  })
  it('HostOrganizationListTest', async function() {
    // Test name: HostOrganizationListTest
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/ |  | 
    await driver.get("http://localhost:8080/")
    // 2 | type | id=inputUsername | s.cotto@gmail.com | 
    await driver.findElement(By.id("inputUsername")).sendKeys("s.cotto@gmail.com")
    // 3 | type | id=inputPassword | sara1234 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("sara1234")
    // 4 | click | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 5 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 6 | setWindowSize | 1280x571 |  | 
    await driver.manage().window().setRect(1280, 571)
    // 7 | runScript | window.scrollTo(0,0) |  | 
    await driver.executeScript("window.scrollTo(0,0)")
    // 8 | click | css=.nav-item:nth-child(3) p |  | 
    await driver.findElement(By.css(".nav-item:nth-child(3) p")).click()
    // 9 | runScript | window.scrollTo(0,0) |  | 
    await driver.executeScript("window.scrollTo(0,0)")
    // 10 | click | id=tipo |  | 
    await driver.findElement(By.id("tipo")).click()
    // 11 | select | id=tipo | label=Organizzazioni Ospitanti | 
    {
      const dropdown = await driver.findElement(By.id("tipo"))
      await dropdown.findElement(By.xpath("//option[. = 'Organizzazioni Ospitanti']")).click()
    }
    // 12 | click | id=hostOrganization |  | 
    await driver.findElement(By.id("hostOrganization")).click()
    // 13 | runScript | window.scrollTo(0,0) |  | 
    await driver.executeScript("window.scrollTo(0,0)")
  })
  it('ViewNotificationExternalTutorTest', async function() {
    // Test name: ViewNotificationExternalTutorTest
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/ |  | 
    await driver.get("http://localhost:8080/")
    // 2 | type | id=inputUsername | s.cotto@gmail.com | 
    await driver.findElement(By.id("inputUsername")).sendKeys("s.cotto@gmail.com")
    // 3 | type | id=inputPassword | sara1234 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("sara1234")
    // 4 | sendKeys | id=inputPassword | ${KEY_ENTER} | 
    await driver.findElement(By.id("inputPassword")).sendKeys(Key.ENTER)
    // 5 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 6 | setWindowSize | 1280x570 |  | 
    await driver.manage().window().setRect(1280, 570)
    // 7 | runScript | window.scrollTo(0,0) |  | 
    await driver.executeScript("window.scrollTo(0,0)")
    // 8 | click | css=.fa-bell |  | 
    await driver.findElement(By.css(".fa-bell")).click()
    // 9 | mouseOver | css=.speech-bubble |  | 
    {
      const element = await driver.findElement(By.css(".speech-bubble"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 10 | mouseOut | css=.speech-bubble |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
  })
  it('ViewProfileExternalTutorTest', async function() {
    // Test name: ViewProfileExternalTutorTest
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/ |  | 
    await driver.get("http://localhost:8080/")
    // 2 | setWindowSize | 1280x570 |  | 
    await driver.manage().window().setRect(1280, 570)
    // 3 | type | id=inputUsername | s.cotto@gmail.com | 
    await driver.findElement(By.id("inputUsername")).sendKeys("s.cotto@gmail.com")
    // 4 | click | css=.form-label-group:nth-child(2) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(2) > label")).click()
    // 5 | type | id=inputPassword | sara1234 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("sara1234")
    // 6 | click | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 7 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 8 | click | id=profile |  | 
    await driver.findElement(By.id("profile")).click()
    // 9 | runScript | window.scrollTo(0,0) |  | 
    await driver.executeScript("window.scrollTo(0,0)")
  })
  it('ViewRequestsListExternalTutorTest', async function() {
    // Test name: ViewRequestsListExternalTutorTest
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/ |  | 
    await driver.get("http://localhost:8080/")
    // 2 | setWindowSize | 910x1153 |  | 
    await driver.manage().window().setRect(910, 1153)
    // 3 | type | id=inputUsername | s.cotto@gmail.com | 
    await driver.findElement(By.id("inputUsername")).sendKeys("s.cotto@gmail.com")
    // 4 | type | id=inputPassword | sara1234 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("sara1234")
    // 5 | sendKeys | id=inputPassword | ${KEY_ENTER} | 
    await driver.findElement(By.id("inputPassword")).sendKeys(Key.ENTER)
    // 6 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 7 | click | css=.navbar-toggler-icon > .icon-menu |  | 
    await driver.findElement(By.css(".navbar-toggler-icon > .icon-menu")).click()
    // 8 | click | css=.nav-item:nth-child(2) p |  | 
    await driver.findElement(By.css(".nav-item:nth-child(2) p")).click()
  })
  it('compileLAExternalTutorTest', async function() {
    // Test name: compileLAExternalTutorTest
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/ |  | 
    await driver.get("http://localhost:8080/")
    // 2 | setWindowSize | 910x1153 |  | 
    await driver.manage().window().setRect(910, 1153)
    // 3 | type | id=inputUsername | g.carpentieri1@studenti.unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("g.carpentieri1@studenti.unisa.it")
    // 4 | type | id=inputPassword | CarpGiovanni1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("CarpGiovanni1")
    // 5 | click | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 6 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 7 | click | css=.navbar-toggler-icon > .icon-menu |  | 
    await driver.findElement(By.css(".navbar-toggler-icon > .icon-menu")).click()
    // 8 | click | css=.nav-item:nth-child(2) p |  | 
    await driver.findElement(By.css(".nav-item:nth-child(2) p")).click()
    // 9 | click | css=.form-label-group:nth-child(2) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(2) > label")).click()
    // 10 | type | id=inputName | Giovanni | 
    await driver.findElement(By.id("inputName")).sendKeys("Giovanni")
    // 11 | type | id=inputSurname | Carpentieri | 
    await driver.findElement(By.id("inputSurname")).sendKeys("Carpentieri")
    // 12 | type | id=inputDate | 0001-11-01 | 
    await driver.findElement(By.id("inputDate")).sendKeys("0001-11-01")
    // 13 | type | id=inputDate | 0019-11-01 | 
    await driver.findElement(By.id("inputDate")).sendKeys("0019-11-01")
    // 14 | type | id=inputDate | 0199-11-01 | 
    await driver.findElement(By.id("inputDate")).sendKeys("0199-11-01")
    // 15 | type | id=inputDate | 1997-11-01 | 
    await driver.findElement(By.id("inputDate")).sendKeys("1997-11-01")
    // 16 | click | css=.form-label-group:nth-child(5) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(5) > label")).click()
    // 17 | type | id=inputTelephone | 3334445557 | 
    await driver.findElement(By.id("inputTelephone")).sendKeys("3334445557")
    // 18 | click | id=M |  | 
    await driver.findElement(By.id("M")).click()
    // 19 | click | css=.form-label-group:nth-child(7) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(7) > label")).click()
    // 20 | type | id=nationality | Italia | 
    await driver.findElement(By.id("nationality")).sendKeys("Italia")
    // 21 | click | id=1st |  | 
    await driver.findElement(By.id("1st")).click()
    // 22 | click | css=.form-label-group:nth-child(9) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(9) > label")).click()
    // 23 | type | id=inputAcademicYear1 | 19 | 
    await driver.findElement(By.id("inputAcademicYear1")).sendKeys("19")
    // 24 | type | id=inputAcademicYear2 | 20 | 
    await driver.findElement(By.id("inputAcademicYear2")).sendKeys("20")
    // 25 | type | id=inputSubjectCode | Informatica, 05121 | 
    await driver.findElement(By.id("inputSubjectCode")).sendKeys("Informatica, 05121")
    // 26 | type | id=inputEmail | g.carpentieri1@studenti.unisa.it | 
    await driver.findElement(By.id("inputEmail")).sendKeys("g.carpentieri1@studenti.unisa.it")
    // 27 | type | id=inputDepartmentSending | Informatica | 
    await driver.findElement(By.id("inputDepartmentSending")).sendKeys("Informatica")
    // 28 | type | id=inputContactName | Simone Risso | 
    await driver.findElement(By.id("inputContactName")).sendKeys("Simone Risso")
    // 29 | type | id=inputContactSending | s.risso@unisa.it 3334445511 | 
    await driver.findElement(By.id("inputContactSending")).sendKeys("s.risso@unisa.it 3334445511")
    // 30 | type | id=inputNameSector | Samsung | 
    await driver.findElement(By.id("inputNameSector")).sendKeys("Samsung")
    // 31 | type | id=inputDepartmentReciving | Informatica | 
    await driver.findElement(By.id("inputDepartmentReciving")).sendKeys("Informatica")
    // 32 | type | id=inputAddress | Via Chon | 
    await driver.findElement(By.id("inputAddress")).sendKeys("Via Chon")
    // 33 | click | css=.form-label-group:nth-child(25) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(25) > label")).click()
    // 34 | type | id=inputWebSite | www.samsung.it | 
    await driver.findElement(By.id("inputWebSite")).sendKeys("www.samsung.it")
    // 35 | select | id=inlineFormCustomSelect | label=Italia | 
    {
      const dropdown = await driver.findElement(By.id("inlineFormCustomSelect"))
      await dropdown.findElement(By.xpath("//option[. = 'Italia']")).click()
    }
    // 36 | click | id=inlineFormCustomSelect |  | 
    await driver.findElement(By.id("inlineFormCustomSelect")).click()
    // 37 | click | css=.form-label-group:nth-child(27) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(27) > label")).click()
    // 38 | type | id=inputSizeEnterprise | 1-50 | 
    await driver.findElement(By.id("inputSizeEnterprise")).sendKeys("1-50")
    // 39 | click | css=.form-label-group:nth-child(28) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(28) > label")).click()
    // 40 | type | id=inputContactRecivingName | Filomena Ferrucci | 
    await driver.findElement(By.id("inputContactRecivingName")).sendKeys("Filomena Ferrucci")
    // 41 | click | css=.form-label-group:nth-child(29) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(29) > label")).click()
    // 42 | type | id=inputContactRecivingPosition | Salerno | 
    await driver.findElement(By.id("inputContactRecivingPosition")).sendKeys("Salerno")
    // 43 | click | css=.form-label-group:nth-child(30) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(30) > label")).click()
    // 44 | type | id=inputMentorName | Alberto Lombardo | 
    await driver.findElement(By.id("inputMentorName")).sendKeys("Alberto Lombardo")
    // 45 | type | id=inputMentorPosition | Fisciano | 
    await driver.findElement(By.id("inputMentorPosition")).sendKeys("Fisciano")
    // 46 | type | id=inputMentorInfo | a.lombardo@libero.it 3334445578 | 
    await driver.findElement(By.id("inputMentorInfo")).sendKeys("a.lombardo@libero.it 3334445578")
    // 47 | click | css=.form-label-group:nth-child(37) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(37) > label")).click()
    // 48 | type | id=inputDateFrom | 02/2020 | 
    await driver.findElement(By.id("inputDateFrom")).sendKeys("02/2020")
    // 49 | type | id=inputDateTo | 09/2021 | 
    await driver.findElement(By.id("inputDateTo")).sendKeys("09/2021")
    // 50 | type | id=inputHourWork | 8 | 
    await driver.findElement(By.id("inputHourWork")).sendKeys("8")
    // 51 | type | id=inputTitle | BigData | 
    await driver.findElement(By.id("inputTitle")).sendKeys("BigData")
    // 52 | click | css=.form-label-group:nth-child(47) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(47) > label")).click()
    // 53 | type | id=inputDetailed | Sviluppo piattaforma web per la gestione dei BigData | 
    await driver.findElement(By.id("inputDetailed")).sendKeys("Sviluppo piattaforma web per la gestione dei BigData")
    // 54 | click | id=inputKnowledge |  | 
    await driver.findElement(By.id("inputKnowledge")).click()
    // 55 | click | id=inputKnowledge |  | 
    await driver.findElement(By.id("inputKnowledge")).click()
    // 56 | type | id=inputKnowledge | javascript,java,nodejs, mongoDB, mocha e chai | 
    await driver.findElement(By.id("inputKnowledge")).sendKeys("javascript,java,nodejs, mongoDB, mocha e chai")
    // 57 | click | css=.form-label-group:nth-child(50) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(50) > label")).click()
    // 58 | click | id=inputKnowledge |  | 
    await driver.findElement(By.id("inputKnowledge")).click()
    // 59 | type | id=inputKnowledge | javascript,java,nodejs, mongoDB, mocha and chai | 
    await driver.findElement(By.id("inputKnowledge")).sendKeys("javascript,java,nodejs, mongoDB, mocha and chai")
    // 60 | click | css=.form-label-group:nth-child(53) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(53) > label")).click()
    // 61 | type | id=inputMonitoring | Report Settimanale | 
    await driver.findElement(By.id("inputMonitoring")).sendKeys("Report Settimanale")
    // 62 | type | id=inputEvaluation | Valutazione settimanale | 
    await driver.findElement(By.id("inputEvaluation")).sendKeys("Valutazione settimanale")
    // 63 | click | id=inputLenguage |  | 
    await driver.findElement(By.id("inputLenguage")).click()
    // 64 | select | id=inputLenguage | label=Inglese | 
    {
      const dropdown = await driver.findElement(By.id("inputLenguage"))
      await dropdown.findElement(By.xpath("//option[. = 'Inglese']")).click()
    }
    // 65 | click | id=inputLenguage |  | 
    await driver.findElement(By.id("inputLenguage")).click()
    // 66 | click | id=B1 |  | 
    await driver.findElement(By.id("B1")).click()
    // 67 | click | id=send |  | 
    await driver.findElement(By.id("send")).click()
    // 68 | open | http://localhost:8080/logout |  | 
    await driver.get("http://localhost:8080/logout")
    // 69 | click | css=.form-label-group:nth-child(1) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(1) > label")).click()
    // 70 | type | id=inputUsername | s.risso@unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("s.risso@unisa.it")
    // 71 | type | id=inputPassword | RisSimone1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("RisSimone1")
    // 72 | click | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 73 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 74 | click | css=.icon-options-vertical |  | 
    await driver.findElement(By.css(".icon-options-vertical")).click()
    // 75 | click | css=.fa-bell |  | 
    await driver.findElement(By.css(".fa-bell")).click()
    // 76 | click | css=.navbar-toggler-icon > .icon-menu |  | 
    await driver.findElement(By.css(".navbar-toggler-icon > .icon-menu")).click()
    // 77 | click | css=.nav-item:nth-child(2) p |  | 
    await driver.findElement(By.css(".nav-item:nth-child(2) p")).click()
    // 78 | click | linkText=Visualizza |  | 
    await driver.findElement(By.linkText("Visualizza")).click()
    // 79 | click | id=approve1 |  | 
    await driver.findElement(By.id("approve1")).click()
    // 80 | click | id=inputCredits |  | 
    await driver.findElement(By.id("inputCredits")).click()
    // 81 | type | id=inputCredits | 11 | 
    await driver.findElement(By.id("inputCredits")).sendKeys("11")
    // 82 | click | id=inputCertificate |  | 
    await driver.findElement(By.id("inputCertificate")).click()
    // 83 | click | id=inputRadio1 |  | 
    await driver.findElement(By.id("inputRadio1")).click()
    // 84 | click | id=send |  | 
    await driver.findElement(By.id("send")).click()
    // 85 | open | http://localhost:8080/logout |  | 
    await driver.get("http://localhost:8080/logout")
    // 86 | click | css=.form-label-group:nth-child(1) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(1) > label")).click()
    // 87 | type | id=inputUsername | a.lombardo@libero.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("a.lombardo@libero.it")
    // 88 | type | id=inputPassword | alberto987 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("alberto987")
    // 89 | sendKeys | id=inputPassword | ${KEY_ENTER} | 
    await driver.findElement(By.id("inputPassword")).sendKeys(Key.ENTER)
    // 90 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 91 | click | css=.topbar-toggler |  | 
    await driver.findElement(By.css(".topbar-toggler")).click()
    // 92 | click | css=.fa-bell |  | 
    await driver.findElement(By.css(".fa-bell")).click()
    // 93 | click | css=.navbar-toggler-icon > .icon-menu |  | 
    await driver.findElement(By.css(".navbar-toggler-icon > .icon-menu")).click()
    // 94 | click | css=.nav-item:nth-child(2) p |  | 
    await driver.findElement(By.css(".nav-item:nth-child(2) p")).click()
    // 95 | click | linkText=Visualizza |  | 
    await driver.findElement(By.linkText("Visualizza")).click()
    // 96 | click | id=approve1 |  | 
    await driver.findElement(By.id("approve1")).click()
    // 97 | click | css=li:nth-child(1) .form-check |  | 
    await driver.findElement(By.css("li:nth-child(1) .form-check")).click()
    // 98 | click | xpath=(//input[@id='inputRadio1'])[2] |  | 
    await driver.findElement(By.xpath("(//input[@id=\'inputRadio1\'])[2]")).click()
    // 99 | click | xpath=(//input[@id='inputRadio2'])[2] |  | 
    await driver.findElement(By.xpath("(//input[@id=\'inputRadio2\'])[2]")).click()
    // 100 | click | css=li:nth-child(3) .form-check |  | 
    await driver.findElement(By.css("li:nth-child(3) .form-check")).click()
    // 101 | click | id=inputRadio3 |  | 
    await driver.findElement(By.id("inputRadio3")).click()
    // 102 | click | id=inputWeeks |  | 
    await driver.findElement(By.id("inputWeeks")).click()
    // 103 | type | id=inputWeeks | 5 | 
    await driver.findElement(By.id("inputWeeks")).sendKeys("5")
    // 104 | click | css=.btn-secondary:nth-child(2) |  | 
    await driver.findElement(By.css(".btn-secondary:nth-child(2)")).click()
  })
})
